/** Demo / fallback data when Firestore reads fail or return empty. */
import { BILLING_PLANS } from '../../shared/billingPlans.js';

/** Knowledge base registry — used in company form dropdowns. */
export const DEMO_KNOWLEDGE = [
  { id: 'demo-kb-1', companyId: 'demo-central-motors', title: 'Central Motors KB', type: 'manual', status: 'active' },
  { id: 'demo-kb-2', companyId: 'demo-golden-cat', title: 'Golden Cat Security FAQ', type: 'manual', status: 'active' },
  { id: 'demo-kb-3', companyId: 'demo-econo-funerals', title: 'Econo Funerals Services', type: 'upload', status: 'active' },
  { id: 'demo-kb-4', companyId: 'demo-ziric-media', title: 'Ziric Media Playbook', type: 'manual', status: 'active' },
  { id: 'demo-kb-5', companyId: 'demo-smile-dentists', title: 'Smile More Dental FAQ', type: 'manual', status: 'active' },
];

const ts = (d) => `${d}T10:00:00.000Z`;

/** Full knowledge items for AI Training Center — Firestore `knowledge` collection schema. */
export const DEMO_KNOWLEDGE_ITEMS = [
  /* ── Central Motors — Documents ── */
  {
    id: 'demo-kn-doc-1',
    companyId: 'demo-central-motors',
    type: 'document',
    title: 'Vehicle Catalogue 2025',
    fileName: 'Vehicle Catalogue 2025.pdf',
    pages: 48,
    status: 'trained',
    uploadedBy: 'John Smith',
    lastTrained: ts('2025-07-14'),
    chunks: 142,
    content: 'Central Motors 2025 vehicle catalogue covering Toyota, Suzuki, and Isuzu models available in Gauteng.',
    createdAt: ts('2025-07-10'),
  },
  {
    id: 'demo-kn-doc-2',
    companyId: 'demo-central-motors',
    type: 'document',
    title: 'Finance Terms',
    fileName: 'Finance Terms.docx',
    pages: 12,
    status: 'trained',
    uploadedBy: 'John Smith',
    lastTrained: ts('2025-07-12'),
    chunks: 38,
    content: 'Central Motors vehicle finance terms including deposit requirements, interest rates, and balloon payment options.',
    createdAt: ts('2025-07-08'),
  },
  {
    id: 'demo-kn-doc-3',
    companyId: 'demo-central-motors',
    type: 'document',
    title: 'Service Price List Q3',
    fileName: 'Service Price List Q3.xlsx',
    pages: 4,
    status: 'trained',
    uploadedBy: 'Sarah van Wyk',
    lastTrained: ts('2025-07-05'),
    chunks: 22,
    createdAt: ts('2025-07-01'),
  },
  /* ── Central Motors — FAQs ── */
  {
    id: 'demo-kn-faq-1',
    companyId: 'demo-central-motors',
    type: 'faq',
    title: 'Business Hours',
    question: 'What are your business hours?',
    answer: 'We operate Monday to Friday from 8:00 AM to 5:00 PM, and Saturdays from 8:00 AM to 1:00 PM. We are closed on Sundays and public holidays.',
    status: 'trained',
    uploadedBy: 'John Smith',
    lastTrained: ts('2025-07-15'),
    chunks: 2,
    createdAt: ts('2025-06-20'),
  },
  {
    id: 'demo-kn-faq-2',
    companyId: 'demo-central-motors',
    type: 'faq',
    title: 'Test Drive Booking',
    question: 'How do I book a test drive?',
    answer: 'You can book a test drive via WhatsApp, by calling +27 11 555 0100, or by visiting our showroom at 42 Main Road, Sandton. Please bring a valid driver\'s licence.',
    status: 'trained',
    uploadedBy: 'John Smith',
    lastTrained: ts('2025-07-15'),
    chunks: 3,
    createdAt: ts('2025-06-20'),
  },
  {
    id: 'demo-kn-faq-3',
    companyId: 'demo-central-motors',
    type: 'faq',
    title: 'Trade-In Valuation',
    question: 'Do you accept trade-ins?',
    answer: 'Yes, we accept trade-ins on all new and pre-owned vehicles. Bring your vehicle for a free valuation — we assess condition, mileage, and market value on the spot.',
    status: 'trained',
    uploadedBy: 'Sarah van Wyk',
    lastTrained: ts('2025-07-10'),
    chunks: 2,
    createdAt: ts('2025-06-25'),
  },
  /* ── Central Motors — Products ── */
  {
    id: 'demo-kn-prod-1',
    companyId: 'demo-central-motors',
    type: 'product',
    title: 'Toyota Corolla 1.8 XS',
    name: 'Toyota Corolla 1.8 XS',
    price: 'R329,900',
    priceNumeric: 329900,
    specifications: '1.8L petrol, CVT automatic, 103 kW, 173 Nm, 6 airbags, reverse camera, Apple CarPlay',
    imageUrl: 'https://images.toyota.co.za/corolla/xs-white.jpg',
    features: 'LED headlights, keyless entry, cruise control, 16" alloy wheels, Toyota Safety Sense',
    warranty: '3 years / 100,000 km manufacturer warranty',
    status: 'trained',
    uploadedBy: 'John Smith',
    lastTrained: ts('2025-07-13'),
    chunks: 5,
    createdAt: ts('2025-06-15'),
  },
  {
    id: 'demo-kn-prod-2',
    companyId: 'demo-central-motors',
    type: 'product',
    title: 'Suzuki Swift 1.2 GL',
    name: 'Suzuki Swift 1.2 GL',
    price: 'R219,900',
    priceNumeric: 219900,
    specifications: '1.2L petrol, 5-speed manual, 61 kW, 113 Nm, ABS, EBD, dual airbags',
    imageUrl: '',
    features: 'Fuel efficient, compact city car, Bluetooth audio, USB port',
    warranty: '3 years / 100,000 km manufacturer warranty',
    status: 'trained',
    uploadedBy: 'John Smith',
    lastTrained: ts('2025-07-13'),
    chunks: 4,
    createdAt: ts('2025-06-15'),
  },
  {
    id: 'demo-kn-prod-3',
    companyId: 'demo-central-motors',
    type: 'product',
    title: 'Isuzu D-Max 250 HO',
    name: 'Isuzu D-Max 250 HO Double Cab',
    price: 'R489,900',
    priceNumeric: 489900,
    specifications: '2.5L turbo-diesel, 6-speed auto, 120 kW, 400 Nm, 4x4, load bin 1,200 kg',
    imageUrl: '',
    features: 'Tow bar ready, diff lock, hill descent control, touchscreen infotainment',
    warranty: '5 years / 120,000 km manufacturer warranty',
    status: 'trained',
    uploadedBy: 'John Smith',
    lastTrained: ts('2025-07-13'),
    chunks: 5,
    createdAt: ts('2025-06-18'),
  },
  /* ── Central Motors — Services ── */
  {
    id: 'demo-kn-svc-1',
    companyId: 'demo-central-motors',
    type: 'service',
    title: 'Vehicle Financing',
    name: 'Vehicle Financing',
    description: 'In-house and partner bank finance for new and pre-owned vehicles. Competitive rates from prime + 1.5%. Balloon and residual options available.',
    requirements: 'Valid SA ID, proof of income (3 months payslips or bank statements), proof of residence, valid driver\'s licence',
    price: 'From prime + 1.5% (subject to credit approval)',
    waitingTime: '24–48 hours for approval',
    status: 'trained',
    uploadedBy: 'John Smith',
    lastTrained: ts('2025-07-12'),
    chunks: 4,
    createdAt: ts('2025-06-10'),
  },
  {
    id: 'demo-kn-svc-2',
    companyId: 'demo-central-motors',
    type: 'service',
    title: 'Full Service & Maintenance',
    name: 'Full Service & Maintenance',
    description: 'Manufacturer-approved service centre for Toyota, Suzuki, and Isuzu. Genuine parts, trained technicians, service history records.',
    requirements: 'Book via WhatsApp or phone. Bring service book and vehicle registration.',
    price: 'From R2,499 (model dependent)',
    waitingTime: 'Same-day for standard services; 1–2 days for major services',
    status: 'trained',
    uploadedBy: 'Sarah van Wyk',
    lastTrained: ts('2025-07-08'),
    chunks: 3,
    createdAt: ts('2025-06-10'),
  },
  /* ── Central Motors — Policies ── */
  {
    id: 'demo-kn-pol-1',
    companyId: 'demo-central-motors',
    type: 'policy',
    title: 'Refund Policy',
    policyType: 'refund',
    content: 'Deposits on vehicle purchases are refundable within 7 business days if finance is declined. A 10% administration fee applies to cancellations after finance approval. Trade-in valuations are valid for 14 days.',
    preview: 'Deposits refundable within 7 days if finance declined...',
    status: 'trained',
    uploadedBy: 'John Smith',
    lastTrained: ts('2025-07-01'),
    chunks: 3,
    createdAt: ts('2025-05-01'),
  },
  {
    id: 'demo-kn-pol-2',
    companyId: 'demo-central-motors',
    type: 'policy',
    title: 'Privacy Policy',
    policyType: 'privacy',
    content: 'Central Motors (Pty) Ltd complies with POPIA. We collect personal information solely for sales, finance applications, and service bookings. Data is not shared with third parties except finance partners with your consent.',
    preview: 'POPIA-compliant data handling for sales and finance...',
    status: 'trained',
    uploadedBy: 'John Smith',
    lastTrained: ts('2025-07-01'),
    chunks: 4,
    createdAt: ts('2025-05-01'),
  },
  {
    id: 'demo-kn-pol-3',
    companyId: 'demo-central-motors',
    type: 'policy',
    title: 'Warranty Policy',
    policyType: 'warranty',
    content: 'All new vehicles carry the manufacturer warranty. Extended warranty and service plans are available at point of sale. Pre-owned vehicles include a 6-month / 10,000 km dealer warranty unless sold voetstoots.',
    preview: 'Manufacturer warranty on new; 6-month dealer warranty on pre-owned...',
    status: 'trained',
    uploadedBy: 'John Smith',
    lastTrained: ts('2025-07-01'),
    chunks: 3,
    createdAt: ts('2025-05-01'),
  },
  {
    id: 'demo-kn-pol-4',
    companyId: 'demo-central-motors',
    type: 'policy',
    title: 'Terms & Conditions',
    policyType: 'terms',
    content: 'All prices include VAT unless stated otherwise. Prices and specifications are subject to change without notice. E&OE. Central Motors reserves the right to withdraw offers. Finance subject to credit approval by registered credit providers.',
    preview: 'Prices include VAT. Finance subject to credit approval...',
    status: 'trained',
    uploadedBy: 'John Smith',
    lastTrained: ts('2025-07-01'),
    chunks: 3,
    createdAt: ts('2025-05-01'),
  },
  /* ── Central Motors — Price Lists ── */
  {
    id: 'demo-kn-price-1',
    companyId: 'demo-central-motors',
    type: 'price-list',
    title: 'New Vehicle Price List — July 2025',
    content: 'Toyota Corolla 1.8 XS — R329,900\nToyota Hilux 2.4 GD-6 Raider — R549,900\nSuzuki Swift 1.2 GL — R219,900\nSuzuki Vitara 1.4T GLX — R389,900\nIsuzu D-Max 250 HO — R489,900\nIsuzu MU-X 3.0 D-Teq — R679,900',
    status: 'trained',
    uploadedBy: 'John Smith',
    lastTrained: ts('2025-07-01'),
    chunks: 6,
    createdAt: ts('2025-07-01'),
  },
  /* ── Central Motors — Website ── */
  {
    id: 'demo-kn-web-1',
    companyId: 'demo-central-motors',
    type: 'website',
    title: 'centralmotors.co.za',
    url: 'https://centralmotors.co.za',
    pagesScraped: 34,
    status: 'trained',
    uploadedBy: 'John Smith',
    lastTrained: ts('2025-07-16'),
    chunks: 89,
    createdAt: ts('2025-07-16'),
  },
  /* ── Central Motors — Manual ── */
  {
    id: 'demo-kn-man-1',
    companyId: 'demo-central-motors',
    type: 'manual',
    title: 'Finance Collection Rules',
    content: 'When a customer enquires about vehicle finance:\n\n1. Always ask for their monthly budget range before quoting specific models.\n2. Minimum deposit is 10% for new vehicles and 15% for pre-owned.\n3. Never guarantee finance approval — always say "subject to credit approval".\n4. If the customer mentions a trade-in, offer a free valuation appointment.\n5. Escalate to a human finance consultant if the customer asks about blacklisted applications or debt review.\n6. Balloon payments are available on select models — explain that a lump sum is due at end of term.\n7. Always mention our partner banks: WesBank, MFC, and Standard Bank.',
    status: 'trained',
    uploadedBy: 'John Smith',
    lastTrained: ts('2025-07-17'),
    chunks: 8,
    createdAt: ts('2025-07-10'),
  },
  /* ── Golden Cat — smaller set ── */
  {
    id: 'demo-kn-gc-faq-1',
    companyId: 'demo-golden-cat',
    type: 'faq',
    title: 'Response Time',
    question: 'How quickly can you deploy a guard?',
    answer: 'For standard deployments we can have a guard on-site within 4 hours in Gauteng. Emergency armed response is available 24/7 with an average response time of 12 minutes.',
    status: 'trained',
    uploadedBy: 'Thabo Mokoena',
    lastTrained: ts('2025-07-10'),
    chunks: 2,
    createdAt: ts('2025-06-01'),
  },
  {
    id: 'demo-kn-gc-svc-1',
    companyId: 'demo-golden-cat',
    type: 'service',
    title: 'Estate Security',
    name: 'Estate Security',
    description: '24/7 armed response and patrol services for residential estates and complexes.',
    requirements: 'Site assessment required before deployment',
    price: 'From R8,500/month per guard',
    waitingTime: '4 hours for standard deployment',
    status: 'trained',
    uploadedBy: 'Thabo Mokoena',
    lastTrained: ts('2025-07-08'),
    chunks: 3,
    createdAt: ts('2025-06-01'),
  },
  /* ── Econo Funerals ── */
  {
    id: 'demo-kn-ef-faq-1',
    companyId: 'demo-econo-funerals',
    type: 'faq',
    title: 'Package Options',
    question: 'What funeral packages do you offer?',
    answer: 'We offer Basic (from R8,500), Standard (from R14,900), and Premium (from R24,500) packages. All include transport, documentation assistance, and a dedicated family liaison.',
    status: 'trained',
    uploadedBy: 'Grace Ndlovu',
    lastTrained: ts('2025-07-05'),
    chunks: 3,
    createdAt: ts('2025-05-15'),
  },
  /* ── Smile More Dentists ── */
  {
    id: 'demo-kn-sm-faq-1',
    companyId: 'demo-smile-dentists',
    type: 'faq',
    title: 'Appointment Booking',
    question: 'How do I book a dental appointment?',
    answer: 'Call +27 12 555 0500, WhatsApp us, or use our online booking form. New patient consultations are R450 and include a full oral examination.',
    status: 'trained',
    uploadedBy: 'Dr. Priya Naidoo',
    lastTrained: ts('2025-07-12'),
    chunks: 2,
    createdAt: ts('2025-06-20'),
  },
];

export const DEMO_TRAINING_HISTORY = [
  {
    id: 'demo-th-1',
    companyId: 'demo-central-motors',
    title: 'Vehicle Catalogue 2025.pdf',
    type: 'document',
    status: 'completed',
    steps: ['uploading', 'extracting', 'chunking', 'embedding', 'training', 'completed'],
    chunksCreated: 142,
    durationSec: 48,
    startedAt: ts('2025-07-14'),
    completedAt: ts('2025-07-14'),
  },
  {
    id: 'demo-th-2',
    companyId: 'demo-central-motors',
    title: 'centralmotors.co.za',
    type: 'website',
    status: 'completed',
    steps: ['uploading', 'extracting', 'chunking', 'embedding', 'training', 'completed'],
    chunksCreated: 89,
    durationSec: 72,
    startedAt: ts('2025-07-16'),
    completedAt: ts('2025-07-16'),
  },
  {
    id: 'demo-th-3',
    companyId: 'demo-central-motors',
    title: 'Finance Terms.docx',
    type: 'document',
    status: 'completed',
    steps: ['uploading', 'extracting', 'chunking', 'embedding', 'training', 'completed'],
    chunksCreated: 38,
    durationSec: 32,
    startedAt: ts('2025-07-12'),
    completedAt: ts('2025-07-12'),
  },
];

export const DEMO_COMPANIES = [
  {
    id: 'demo-central-motors',
    name: 'Central Motors',
    industry: 'Automotive',
    plan: 'business',
    status: 'active',
    owner: 'John Smith',
    ownerEmail: 'john@centralmotors.co.za',
    ownerPhone: '+27 82 555 0101',
    email: 'info@centralmotors.co.za',
    phone: '+27 11 555 0100',
    website: 'https://centralmotors.co.za',
    logoUrl: '',
    knowledgeBaseId: 'demo-kb-1',
    knowledgeBaseName: 'Central Motors KB',
    agentId: 'demo-agent-1',
    agentName: 'Sarah',
    whatsappNumber: '+27 71 000 1234',
    whatsappConnected: true,
    openAiApiKey: 'sk-demo-central-motors-key',
    aiModel: 'gpt-4o-mini',
    aiTemperature: 0.7,
    whatsappBusinessId: 'WABA-CM-001',
    whatsappWebhookUrl: 'https://api.ziric.ai/webhook/central-motors',
    knowledgeAutoSync: true,
    knowledgeMaxDocs: 500,
    usage: { messages: 4820, tokens: 128400, period: 'This month' },
    billing: { planAmount: BILLING_PLANS.business.price, currency: 'ZAR', status: 'paid', cycle: 'monthly' },
    settings: {},
  },
  {
    id: 'demo-golden-cat',
    name: 'Golden Cat Security',
    industry: 'Security',
    plan: 'enterprise',
    status: 'active',
    owner: 'Thabo Mokoena',
    ownerEmail: 'thabo@goldencat.co.za',
    ownerPhone: '+27 83 555 0202',
    email: 'support@goldencat.co.za',
    phone: '+27 11 555 0200',
    website: 'https://goldencat.co.za',
    logoUrl: '',
    knowledgeBaseId: 'demo-kb-2',
    knowledgeBaseName: 'Golden Cat Security FAQ',
    agentId: 'demo-agent-2',
    agentName: 'Marcus',
    whatsappNumber: '+27 82 555 7890',
    whatsappConnected: true,
    openAiApiKey: 'sk-demo-goldencat-key',
    aiModel: 'gpt-4o',
    aiTemperature: 0.5,
    whatsappBusinessId: 'WABA-GC-002',
    whatsappWebhookUrl: 'https://api.ziric.ai/webhook/golden-cat',
    knowledgeAutoSync: true,
    knowledgeMaxDocs: 1000,
    usage: { messages: 3156, tokens: 98400, period: 'This month' },
    billing: { planAmount: null, currency: 'ZAR', status: 'paid', cycle: 'monthly' },
    settings: {},
  },
  {
    id: 'demo-econo-funerals',
    name: 'Econo Funerals',
    industry: 'Funeral Services',
    plan: 'starter',
    status: 'active',
    owner: 'Grace Ndlovu',
    ownerEmail: 'grace@ecnfunerals.co.za',
    ownerPhone: '+27 84 555 0303',
    email: 'info@ecnfunerals.co.za',
    phone: '+27 31 555 0300',
    website: 'https://ecnfunerals.co.za',
    logoUrl: '',
    knowledgeBaseId: 'demo-kb-3',
    knowledgeBaseName: 'Econo Funerals Services',
    agentId: 'demo-agent-3',
    agentName: 'Grace',
    whatsappNumber: '+27 72 555 4567',
    whatsappConnected: true,
    openAiApiKey: 'sk-demo-econo-key',
    aiModel: 'gpt-4o-mini',
    aiTemperature: 0.4,
    whatsappBusinessId: 'WABA-EF-003',
    whatsappWebhookUrl: 'https://api.ziric.ai/webhook/econo-funerals',
    knowledgeAutoSync: false,
    knowledgeMaxDocs: 200,
    usage: { messages: 892, tokens: 28400, period: 'This month' },
    billing: { planAmount: BILLING_PLANS.starter.price, currency: 'ZAR', status: 'paid', cycle: 'monthly' },
    settings: {},
  },
  {
    id: 'demo-ziric-media',
    name: 'Ziric Media',
    industry: 'Media & Marketing',
    plan: 'business',
    status: 'active',
    owner: 'Sarah van der Merwe',
    ownerEmail: 'sarah@ziricmedia.co.za',
    ownerPhone: '+27 71 555 0404',
    email: 'hello@ziricmedia.co.za',
    phone: '+27 21 555 0400',
    website: 'https://ziricmedia.co.za',
    logoUrl: '',
    knowledgeBaseId: 'demo-kb-4',
    knowledgeBaseName: 'Ziric Media Playbook',
    agentId: 'demo-agent-4',
    agentName: 'Lebo',
    whatsappNumber: '+27 76 555 8901',
    whatsappConnected: true,
    openAiApiKey: 'sk-demo-ziric-media-key',
    aiModel: 'gpt-4o-mini',
    aiTemperature: 0.8,
    whatsappBusinessId: 'WABA-ZM-004',
    whatsappWebhookUrl: 'https://api.ziric.ai/webhook/ziric-media',
    knowledgeAutoSync: true,
    knowledgeMaxDocs: 750,
    usage: { messages: 2240, tokens: 67200, period: 'This month' },
    billing: { planAmount: BILLING_PLANS.business.price, currency: 'ZAR', status: 'paid', cycle: 'monthly' },
    settings: {},
  },
  {
    id: 'demo-smile-dentists',
    name: 'Smile More Dentists',
    industry: 'Healthcare / Dental',
    plan: 'business',
    status: 'trial',
    owner: 'Dr. Priya Naidoo',
    ownerEmail: 'priya@smilemore.co.za',
    ownerPhone: '+27 82 555 0505',
    email: 'bookings@smilemore.co.za',
    phone: '+27 12 555 0500',
    website: 'https://smilemore.co.za',
    logoUrl: '',
    knowledgeBaseId: 'demo-kb-5',
    knowledgeBaseName: 'Smile More Dental FAQ',
    agentId: 'demo-agent-5',
    agentName: 'Priya',
    whatsappNumber: '+27 83 555 6789',
    whatsappConnected: false,
    openAiApiKey: '',
    aiModel: 'gpt-4o-mini',
    aiTemperature: 0.6,
    whatsappBusinessId: '',
    whatsappWebhookUrl: '',
    knowledgeAutoSync: true,
    knowledgeMaxDocs: 300,
    usage: { messages: 148, tokens: 8200, period: 'This month' },
    billing: { planAmount: BILLING_PLANS.business.price, currency: 'ZAR', status: 'pending', cycle: 'monthly' },
    settings: {},
  },
];

const DEMO_AGENT_DEFAULTS = {
  knowledgeSources: {
    pdfs: true,
    docx: false,
    faqs: true,
    websiteUrl: true,
    manualKnowledge: true,
    policies: false,
    products: true,
    services: true,
  },
  channels: {
    whatsapp: true,
    websiteChat: false,
    facebookMessenger: false,
    instagram: false,
    telegram: false,
    email: false,
  },
  temperature: 0.7,
  maxTokens: 1024,
  memory: true,
  reasoningLevel: 'standard',
  humanTakeover: true,
  officeHours: 'Mon–Fri 08:00–17:00',
};

export const DEMO_AGENTS = [
  {
    id: 'demo-agent-1',
    companyId: 'demo-central-motors',
    ...DEMO_AGENT_DEFAULTS,
    name: 'Sarah',
    department: 'Sales',
    role: 'sales_consultant',
    roleLabel: 'Sales Consultant',
    avatar: '🤖',
    avatarUrl: '',
    personality: 'sales_driven',
    model: 'gpt-4o',
    temperature: 0.7,
    maxTokens: 2048,
    memory: true,
    reasoningLevel: 'high',
    greetingMessage: 'Hi there! I\'m Sarah from Central Motors. Looking for your next vehicle? I\'d love to help you find the perfect match.',
    fallbackMessage: 'Let me connect you with one of our sales consultants who can assist you further.',
    humanTakeover: true,
    officeHours: 'Mon–Sat 08:00–18:00',
    escalationRules: 'Escalate to human when customer requests test drive booking or financing approval.',
    systemPrompt: 'You are Sarah, a knowledgeable sales consultant at Central Motors in South Africa.',
    whatsappNumber: '+27 71 000 1234',
    whatsappConnected: true,
    knowledgeBaseId: 'demo-kb-1',
    status: 'active',
    conversations: 2134,
    resolvedPct: 87,
    channels: { ...DEMO_AGENT_DEFAULTS.channels, websiteChat: true },
  },
  {
    id: 'demo-agent-2',
    companyId: 'demo-golden-cat',
    ...DEMO_AGENT_DEFAULTS,
    name: 'Marcus',
    department: 'Operations',
    role: 'security_advisor',
    roleLabel: 'Security Advisor',
    avatar: '🛡️',
    avatarUrl: '',
    personality: 'professional',
    model: 'gpt-4o',
    temperature: 0.5,
    maxTokens: 1536,
    memory: true,
    reasoningLevel: 'high',
    greetingMessage: 'Good day. I\'m Marcus from Golden Cat Security. How can I help protect what matters to you today?',
    fallbackMessage: 'I\'ll arrange for a security specialist to contact you shortly.',
    humanTakeover: true,
    officeHours: '24/7',
    escalationRules: 'Immediate escalation for emergency dispatch or armed response requests.',
    systemPrompt: 'You are Marcus, a professional security advisor at Golden Cat Security.',
    whatsappNumber: '+27 82 555 7890',
    whatsappConnected: true,
    knowledgeBaseId: 'demo-kb-2',
    status: 'active',
    conversations: 892,
    resolvedPct: 92,
  },
  {
    id: 'demo-agent-3',
    companyId: 'demo-econo-funerals',
    ...DEMO_AGENT_DEFAULTS,
    name: 'Grace',
    department: 'Client Care',
    role: 'compassion_counselor',
    roleLabel: 'Compassion Counselor',
    avatar: '💐',
    avatarUrl: '',
    personality: 'empathetic',
    model: 'gpt-4o-mini',
    temperature: 0.4,
    maxTokens: 1024,
    memory: true,
    reasoningLevel: 'standard',
    greetingMessage: 'Hello, I\'m Grace from Econo Funerals. I\'m here to support you with care and compassion. How may I assist you?',
    fallbackMessage: 'A member of our care team will reach out to you personally.',
    humanTakeover: true,
    officeHours: 'Mon–Sun 06:00–22:00',
    escalationRules: 'Always escalate grief counseling, payment disputes, and urgent arrangements to human staff.',
    systemPrompt: 'You are Grace, a compassionate counselor at Econo Funerals.',
    whatsappNumber: '+27 72 555 4567',
    whatsappConnected: true,
    knowledgeBaseId: 'demo-kb-3',
    status: 'active',
    conversations: 567,
    resolvedPct: 78,
    knowledgeSources: { ...DEMO_AGENT_DEFAULTS.knowledgeSources, policies: true },
  },
  {
    id: 'demo-agent-4',
    companyId: 'demo-ziric-media',
    ...DEMO_AGENT_DEFAULTS,
    name: 'Lebo',
    department: 'Marketing',
    role: 'marketing_assistant',
    roleLabel: 'Marketing Assistant',
    avatar: '📣',
    avatarUrl: '',
    personality: 'friendly',
    model: 'gpt-4o-mini',
    temperature: 0.8,
    maxTokens: 2048,
    memory: true,
    reasoningLevel: 'standard',
    greetingMessage: 'Hey! I\'m Lebo from Ziric Media. Ready to boost your brand? Tell me about your marketing goals.',
    fallbackMessage: 'Let me loop in our campaign strategist to help with that.',
    humanTakeover: true,
    officeHours: 'Mon–Fri 09:00–17:00',
    escalationRules: 'Escalate custom campaign quotes and contract discussions.',
    systemPrompt: 'You are Lebo, an enthusiastic marketing assistant at Ziric Media.',
    whatsappNumber: '+27 76 555 8901',
    whatsappConnected: true,
    knowledgeBaseId: 'demo-kb-4',
    status: 'active',
    conversations: 1240,
    resolvedPct: 85,
    channels: { ...DEMO_AGENT_DEFAULTS.channels, websiteChat: true, instagram: true },
  },
  {
    id: 'demo-agent-5',
    companyId: 'demo-smile-dentists',
    ...DEMO_AGENT_DEFAULTS,
    name: 'Priya',
    department: 'Front Desk',
    role: 'receptionist',
    roleLabel: 'Receptionist',
    avatar: '📅',
    avatarUrl: '',
    personality: 'friendly',
    model: 'gpt-4o-mini',
    temperature: 0.6,
    maxTokens: 1024,
    memory: true,
    reasoningLevel: 'standard',
    greetingMessage: 'Welcome to Smile More Dentists! I\'m Priya. Would you like to book an appointment or ask about our services?',
    fallbackMessage: 'Our reception team will get back to you during office hours.',
    humanTakeover: true,
    officeHours: 'Mon–Fri 08:00–16:30',
    escalationRules: 'Escalate dental emergencies and insurance pre-authorizations.',
    systemPrompt: 'You are Priya, the friendly receptionist at Smile More Dentists.',
    whatsappNumber: '+27 83 555 6789',
    whatsappConnected: false,
    knowledgeBaseId: 'demo-kb-5',
    status: 'inactive',
    conversations: 148,
    resolvedPct: 65,
  },
];

/** Summary rows for dashboard widgets (derived from inbox seed). */
export const DEMO_CONVERSATIONS = [
  { id: 'conv-john-smith', companyId: 'demo-central-motors', customerName: 'John Smith', companyName: 'Central Motors', lastMessage: "I'm looking for a Toyota Hilux.", status: 'in_progress', time: 'Just now', channel: 'whatsapp' },
  { id: 'conv-sarah-jones', companyId: 'demo-central-motors', customerName: 'Sarah Jones', companyName: 'Central Motors', lastMessage: 'Can you help me book a test drive?', status: 'in_progress', time: '2m ago', channel: 'whatsapp' },
  { id: 'conv-david-finance', companyId: 'demo-central-motors', customerName: 'David Nkosi', companyName: 'Central Motors', lastMessage: 'Finance application — what deposit do I need?', status: 'human_takeover', time: '12m ago', channel: 'whatsapp' },
  { id: 'conv-peter-funerals', companyId: 'demo-econo-funerals', customerName: 'Peter Molefe', companyName: 'Econo Funerals', lastMessage: 'Funeral packages for my father', status: 'in_progress', time: '18m ago', channel: 'whatsapp' },
  { id: 'conv-james-security', companyId: 'demo-golden-cat', customerName: 'James K.', companyName: 'Golden Cat Security', lastMessage: 'I need a guard for my estate this weekend', status: 'new', time: '8m ago', channel: 'whatsapp' },
];

const inboxMsg = (id, role, message, time, senderName) => ({
  id,
  role,
  message,
  time,
  ...(senderName ? { senderName } : {}),
});

/** Full inbox seed — conversations, messages, customer profiles. */
export const DEMO_INBOX_CONVERSATIONS = [
  {
    id: 'conv-john-smith',
    companyId: 'demo-central-motors',
    companyName: 'Central Motors',
    customerId: 'cust-john-smith',
    customerName: 'John Smith',
    phone: '+27 84 900 0523',
    email: 'johndoe@email.com',
    channel: 'whatsapp',
    status: 'in_progress',
    mode: 'ai',
    unread: true,
    online: true,
    lastSeenMinutes: null,
    preview: 'Toyota enquiry...',
    lastMessage: "I'm looking for a Toyota Hilux.",
    time: 'Just now',
    assignedTo: null,
    leadScore: 92,
    lastOrder: '—',
    conversationCount: 3,
    lastPurchase: '—',
    aiConfidence: 97,
    knowledgeUsed: 'Toyota Catalogue',
    suggestedReply: 'We have the Toyota Hilux 2.4 GD-6 Raider from R549,900. Would you like to book a test drive or discuss finance options?',
    tags: ['VIP', 'Hot Lead', 'Finance'],
    notes: '',
    messages: [
      inboxMsg('m-j1', 'customer', 'Hello', '09:14'),
      inboxMsg('m-j2', 'ai', 'Hello John. How may I help you today?', '09:14'),
      inboxMsg('m-j3', 'customer', "I'm looking for a Toyota Hilux.", '09:15'),
    ],
  },
  {
    id: 'conv-sarah-jones',
    companyId: 'demo-central-motors',
    companyName: 'Central Motors',
    customerId: 'cust-sarah-jones',
    customerName: 'Sarah Jones',
    phone: '+27 83 444 5566',
    email: 'sarah.j@outlook.com',
    channel: 'whatsapp',
    status: 'in_progress',
    mode: 'ai',
    unread: false,
    online: false,
    lastSeenMinutes: 2,
    preview: 'Test drive booking...',
    lastMessage: 'Can you help me book a test drive?',
    time: '2m ago',
    assignedTo: null,
    leadScore: 74,
    lastOrder: 'Service — Corolla (Mar 2025)',
    conversationCount: 7,
    lastPurchase: 'R2,499 service (Mar 2025)',
    aiConfidence: 91,
    knowledgeUsed: 'Business Hours FAQ',
    suggestedReply: 'Absolutely! We offer test drives Mon–Sat. Which model would you like to drive, and what day suits you best?',
    tags: ['Sales', 'VIP'],
    notes: 'Repeat customer — owns Corolla. Upsell to new model.',
    messages: [
      inboxMsg('m-s1', 'customer', 'Hi, I bought my Corolla from you last year', '08:52'),
      inboxMsg('m-s2', 'ai', 'Welcome back, Sarah! Great to hear from you again. How can I assist?', '08:52'),
      inboxMsg('m-s3', 'customer', 'Can you help me book a test drive?', '08:54'),
    ],
  },
  {
    id: 'conv-david-finance',
    companyId: 'demo-central-motors',
    companyName: 'Central Motors',
    customerId: 'cust-david-nkosi',
    customerName: 'David Nkosi',
    phone: '+27 71 888 9900',
    email: 'david.nkosi@yahoo.com',
    channel: 'whatsapp',
    status: 'human_takeover',
    mode: 'human',
    unread: true,
    online: false,
    lastSeenMinutes: 12,
    preview: 'Finance application',
    lastMessage: 'Finance application — what deposit do I need?',
    time: '12m ago',
    assignedTo: 'Sarah',
    leadScore: 68,
    lastOrder: '—',
    conversationCount: 2,
    lastPurchase: '—',
    aiConfidence: 72,
    knowledgeUsed: 'Finance Terms',
    suggestedReply: 'For new vehicles the minimum deposit is 10%. I can connect you with our finance consultant for a personalised quote.',
    tags: ['Sales', 'Hot Lead'],
    notes: 'Customer wants financing. Call tomorrow.',
    messages: [
      inboxMsg('m-d1', 'customer', 'I want to apply for vehicle finance', '08:30'),
      inboxMsg('m-d2', 'ai', 'I can help with that. Are you looking at a new or pre-owned vehicle?', '08:30'),
      inboxMsg('m-d3', 'customer', 'Finance application — what deposit do I need?', '08:32'),
      inboxMsg('m-d4', 'human', 'Hi David, I\'m Sarah from Central Motors finance. Minimum deposit is 10% on new vehicles. Shall I call you today?', '08:35', 'Sarah'),
    ],
  },
  {
    id: 'conv-peter-funerals',
    companyId: 'demo-econo-funerals',
    companyName: 'Econo Funerals',
    customerId: 'cust-peter-molefe',
    customerName: 'Peter Molefe',
    phone: '+27 84 222 3344',
    email: '',
    channel: 'whatsapp',
    status: 'in_progress',
    mode: 'ai',
    unread: false,
    online: false,
    lastSeenMinutes: 18,
    preview: 'Funeral packages',
    lastMessage: 'Funeral packages for my father',
    time: '18m ago',
    assignedTo: null,
    leadScore: 90,
    lastOrder: '—',
    conversationCount: 1,
    lastPurchase: '—',
    aiConfidence: 88,
    knowledgeUsed: 'Econo Funerals Services',
    suggestedReply: 'I\'m sorry for your loss, Peter. We offer Basic (from R8,500), Standard (from R14,900), and Premium (from R24,500) packages. Would you like a breakdown of what each includes?',
    tags: ['Support', 'Hot Lead'],
    notes: '',
    messages: [
      inboxMsg('m-p1', 'customer', 'Good morning', '07:45'),
      inboxMsg('m-p2', 'ai', 'Good morning, Peter. I\'m Grace from Econo Funerals. I\'m here to support you with care. How may I assist?', '07:45'),
      inboxMsg('m-p3', 'customer', 'Funeral packages for my father', '07:48'),
    ],
  },
  {
    id: 'conv-james-security',
    companyId: 'demo-golden-cat',
    companyName: 'Golden Cat Security',
    customerId: 'cust-james-k',
    customerName: 'James K.',
    phone: '+27 82 555 1212',
    email: 'james.k@gmail.com',
    channel: 'whatsapp',
    status: 'new',
    mode: 'ai',
    unread: true,
    online: true,
    lastSeenMinutes: null,
    preview: 'Estate security guard...',
    lastMessage: 'I need a guard for my estate this weekend',
    time: '8m ago',
    assignedTo: null,
    leadScore: 55,
    lastOrder: '—',
    conversationCount: 1,
    lastPurchase: '—',
    aiConfidence: 85,
    knowledgeUsed: 'Golden Cat Security FAQ',
    suggestedReply: 'We can deploy a guard within 4 hours in Gauteng. How many guards do you need and what are your estate access requirements?',
    tags: ['New Lead', 'Sales'],
    notes: '',
    messages: [
      inboxMsg('m-k1', 'customer', 'I need a guard for my estate this weekend', '09:05'),
    ],
  },
];

export const DEMO_INBOX_TAG_OPTIONS = [
  'New Lead',
  'VIP',
  'Complaint',
  'Sales',
  'Support',
  'Hot Lead',
];

export const DEMO_ANALYTICS_SERIES = {
  labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
  conversations: [124, 156, 142, 189, 201, 98, 112],
  aiHandled: [98, 132, 118, 165, 178, 82, 95],
  whatsappMessages: [420, 510, 480, 620, 680, 310, 390],
  aiReplies: [380, 465, 440, 590, 640, 290, 360],
};

export const DEMO_ANALYTICS_ROWS = [
  { date: '2025-07-17', conversations: 201, tokensUsed: 48200, avgResponseTimeMs: 1240, whatsappMessages: 680, satisfaction: 4.6, activeCompanies: 5 },
  { date: '2025-07-16', conversations: 189, tokensUsed: 45100, avgResponseTimeMs: 1180, whatsappMessages: 620, satisfaction: 4.5, activeCompanies: 5 },
  { date: '2025-07-15', conversations: 156, tokensUsed: 39800, avgResponseTimeMs: 1320, whatsappMessages: 510, satisfaction: 4.4, activeCompanies: 5 },
  { date: '2025-07-14', conversations: 142, tokensUsed: 36500, avgResponseTimeMs: 1410, whatsappMessages: 480, satisfaction: 4.3, activeCompanies: 5 },
  { date: '2025-07-13', conversations: 98, tokensUsed: 22100, avgResponseTimeMs: 980, whatsappMessages: 310, satisfaction: 4.7, activeCompanies: 4 },
];

export const PLAN_AMOUNTS = {
  starter: BILLING_PLANS.starter.price,
  professional: BILLING_PLANS.professional.price,
  business: BILLING_PLANS.business.price,
  enterprise: BILLING_PLANS.enterprise.price,
};

/** Mission Control / AI Operations Center — live-style demo data. */
export const DEMO_OPERATIONS = {
  metrics: {
    aiEmployeesOnline: 427,
    activeConversations: 143,
    avgResponseTimeSec: 1.3,
    customerSatisfaction: 97,
    messagesToday: 12864,
    openAiTokensUsed: 8200000,
    estimatedRevenue: 245600,
    humanTakeovers: 12,
    aiSuccessRate: 98.4,
    companiesOnline: 5,
  },
  trends: {
    aiEmployeesOnline: 4.2,
    activeConversations: 11.8,
    avgResponseTimeSec: -8.5,
    customerSatisfaction: 2.1,
    messagesToday: 18.4,
    openAiTokensUsed: 6.7,
    estimatedRevenue: 22.3,
    humanTakeovers: -15.0,
    aiSuccessRate: 0.6,
    companiesOnline: 0,
  },
  activityFeed: [
    { id: 'act-1', type: 'ai_reply', icon: 'fa-robot', color: 'green', text: '<strong>Sarah</strong> replied to John Smith at Central Motors', detail: 'Shared Hilux 2.4 GD-6 pricing from R549,900', time: 'Just now', ago: '0s' },
    { id: 'act-2', type: 'new_conversation', icon: 'fa-comments', color: 'blue', text: 'New conversation from <strong>James K.</strong>', detail: 'Golden Cat Security — estate guard request', time: '8s ago', ago: '8s' },
    { id: 'act-3', type: 'knowledge', icon: 'fa-book', color: 'yellow', text: 'Knowledge used: <strong>Finance Terms</strong>', detail: 'Central Motors — David Nkosi finance enquiry', time: '45s ago', ago: '45s' },
    { id: 'act-4', type: 'human_takeover', icon: 'fa-user-shield', color: 'red', text: '<strong>Sarah</strong> took over conversation', detail: 'David Nkosi — finance deposit question', time: '2m ago', ago: '2m' },
    { id: 'act-5', type: 'ai_reply', icon: 'fa-robot', color: 'green', text: '<strong>Grace</strong> replied to Peter Molefe', detail: 'Econo Funerals — compassionate package overview', time: '3m ago', ago: '3m' },
    { id: 'act-6', type: 'conversion', icon: 'fa-chart-line', color: 'green', text: 'Lead score increased for <strong>John Smith</strong>', detail: 'Central Motors — score 92 (+4)', time: '5m ago', ago: '5m' },
    { id: 'act-7', type: 'new_conversation', icon: 'fa-comments', color: 'blue', text: 'New conversation from <strong>Sarah Jones</strong>', detail: 'Central Motors — test drive booking', time: '6m ago', ago: '6m' },
    { id: 'act-8', type: 'knowledge', icon: 'fa-book', color: 'yellow', text: 'Knowledge used: <strong>Vehicle Catalogue 2025</strong>', detail: 'Central Motors — John Smith Hilux enquiry', time: '8m ago', ago: '8m' },
    { id: 'act-9', type: 'ai_reply', icon: 'fa-robot', color: 'green', text: '<strong>Marcus</strong> replied to James K.', detail: 'Golden Cat — 4-hour guard deployment info', time: '10m ago', ago: '10m' },
    { id: 'act-10', type: 'system', icon: 'fa-bolt', color: 'grey', text: 'Queue processed 847 messages', detail: 'Peak hour throughput — avg 1.2s response', time: '12m ago', ago: '12m' },
  ],
  humanTakeovers: [
    { id: 'ht-1', customer: 'David Nkosi', company: 'Central Motors', agent: 'Sarah', reason: 'Finance deposit consultation', time: '12m ago' },
    { id: 'ht-2', customer: 'Linda M.', company: 'Golden Cat Security', agent: 'Marcus', reason: 'Emergency armed response', time: '34m ago' },
    { id: 'ht-3', customer: 'Thabo P.', company: 'Econo Funerals', agent: 'Grace', reason: 'Grief counseling escalation', time: '1h ago' },
    { id: 'ht-4', customer: 'Mike van der Berg', company: 'Central Motors', agent: 'John Smith', reason: 'Trade-in valuation photos', time: '2h ago' },
  ],
  trendingQuestions: [
    { question: 'What are your business hours?', count: 284, company: 'Central Motors' },
    { question: 'How do I book a test drive?', count: 196, company: 'Central Motors' },
    { question: 'What deposit do I need for finance?', count: 178, company: 'Central Motors' },
    { question: 'Do you have the Toyota Hilux in stock?', count: 142, company: 'Central Motors' },
    { question: 'How quickly can you deploy a guard?', count: 98, company: 'Golden Cat Security' },
    { question: 'What funeral packages do you offer?', count: 87, company: 'Econo Funerals' },
  ],
  agentLeaderboard: [
    { rank: 1, name: 'Sarah', company: 'Central Motors', messages: 4820, satisfaction: 97, conversion: 34 },
    { rank: 2, name: 'Marcus', company: 'Golden Cat Security', messages: 3156, satisfaction: 94, conversion: 28 },
    { rank: 3, name: 'Grace', company: 'Econo Funerals', messages: 892, satisfaction: 96, conversion: 41 },
    { rank: 4, name: 'Lebo', company: 'Ziric Media', messages: 2240, satisfaction: 91, conversion: 22 },
  ],
  companyLeaderboard: [
    { rank: 1, name: 'Central Motors', messages: 4820, satisfaction: 97, revenue: 98500, agents: 1 },
    { rank: 2, name: 'Golden Cat Security', messages: 3156, satisfaction: 94, revenue: 67200, agents: 1 },
    { rank: 3, name: 'Ziric Media', messages: 2240, satisfaction: 91, revenue: 44800, agents: 1 },
    { rank: 4, name: 'Econo Funerals', messages: 892, satisfaction: 96, revenue: 35100, agents: 1 },
  ],
  hourlyConversations: [12, 8, 5, 4, 6, 18, 42, 68, 94, 112, 128, 134, 118, 102, 96, 88, 76, 64, 52, 38, 28, 22, 18, 14],
  isDemo: true,
};

export function demoDashboardStats() {
  const today = DEMO_ANALYTICS_ROWS[0];
  return {
    totalCompanies: DEMO_COMPANIES.length,
    activeAgents: DEMO_AGENTS.filter((a) => a.status === 'active').length,
    totalCustomers: 1847,
    conversationsToday: today.conversations,
    whatsappMessagesToday: today.whatsappMessages,
    openAiTokensToday: today.tokensUsed,
    trends: {
      companies: 8.2,
      agents: 12.5,
      customers: 5.4,
      conversations: 14.1,
      whatsapp: 9.8,
      tokens: -3.2,
    },
    companies: DEMO_COMPANIES,
    agents: DEMO_AGENTS,
    conversations: DEMO_CONVERSATIONS,
    analytics: DEMO_ANALYTICS_ROWS,
    chartSeries: DEMO_ANALYTICS_SERIES,
    isDemo: true,
    errors: [],
  };
}

export function demoInboxMessages(conversationId) {
  const conv = DEMO_INBOX_CONVERSATIONS.find((c) => c.id === conversationId);
  return conv?.messages || DEMO_INBOX_CONVERSATIONS[0]?.messages || [];
}

export function getDemoInboxConversation(id) {
  return DEMO_INBOX_CONVERSATIONS.find((c) => c.id === id) || null;
}

export function filterDemoInboxByCompany(companyId) {
  if (!companyId) return [...DEMO_INBOX_CONVERSATIONS];
  return DEMO_INBOX_CONVERSATIONS.filter((c) => c.companyId === companyId);
}

/** Full CRM profiles — admin fallback when API unavailable. */
export const DEMO_CUSTOMERS = [
  {
    id: '27849000523',
    phone: '27849000523',
    phoneDisplay: '+27 84 900 0523',
    name: 'John Smith',
    email: 'johndoe@email.com',
    companyId: 'demo-central-motors',
    companyName: 'Central Motors',
    status: 'in_progress',
    online: true,
    customerSince: '2026-07-14T09:00:00.000Z',
    leadScore: 92,
    leadScoreBreakdown: { conversationFrequency: 18, questionsAsked: 16, productsViewed: 15, positiveSentiment: 14, purchaseIntent: 17, responseSpeed: 12 },
    averageSentiment: 'positive',
    sentimentLabel: 'Positive',
    aiConfidence: 98,
    assignedAiEmployee: 'Sarah',
    assignedHumanAgent: null,
    tags: ['VIP', 'Hot Lead', 'Finance'],
    aiSummary: 'John Smith is a high-intent buyer at Central Motors interested in a white Toyota Hilux Double Cab within a R450,000 budget. He has asked about vehicle finance three times, mentioned a trade-in on his 2019 Ford Ranger, and prefers white exterior with black interior. Sarah (AI) has shared Hilux specs, finance terms, and trade-in valuation info. Recommended next step: send finance application link and book test drive.',
    recommendedAction: { action: 'Offer finance application link and schedule Hilux test drive', reason: 'Customer has asked about financing three times and confirmed budget + trade-in.', confidence: 96 },
    interests: { vehicle: 'Toyota Hilux 2.4 GD-6 Double Cab', color: 'White', budget: 'R450,000', finance: true, tradeIn: '2019 Ford Ranger' },
    notesList: [
      { id: 'note-j1', text: 'Repeat enquiry — previously visited showroom in June. Very motivated buyer.', author: 'Sarah (AI)', createdAt: '2026-07-15T11:20:00.000Z' },
      { id: 'note-j2', text: 'Finance pre-check requested. Minimum 10% deposit confirmed. Trade-in valuation pending photos.', author: 'John Smith (Sales)', createdAt: '2026-07-18T09:45:00.000Z' },
    ],
    tasks: [
      { id: 'task-j1', title: 'Call customer re: finance application', deadline: '2026-07-21T17:00:00.000Z', priority: 'high', assignedTo: 'Sarah', done: false, createdAt: '2026-07-19T08:00:00.000Z' },
      { id: 'task-j2', title: 'Book Hilux test drive — white model', deadline: '2026-07-22T12:00:00.000Z', priority: 'medium', assignedTo: 'Unassigned', done: false, createdAt: '2026-07-20T10:15:00.000Z' },
    ],
    documents: [
      { id: 'doc-j1', name: 'Trade-in photos — Ranger', type: 'image', uploadedAt: '2026-07-17T15:30:00.000Z' },
      { id: 'doc-j2', name: 'ID copy — John Smith.pdf', type: 'pdf', uploadedAt: '2026-07-18T09:00:00.000Z' },
    ],
    orders: [{ id: 'ord-j0', label: 'No completed purchase yet', status: 'pending', amount: null, date: null }],
    timeline: [
      { id: 'tl-j1', type: 'created', title: 'Customer Created', description: 'Profile created from WhatsApp inbound.', createdAt: '2026-07-14T09:00:00.000Z' },
      { id: 'tl-j2', type: 'whatsapp', title: 'WhatsApp Message', description: "Hello — I'm looking for a Toyota Hilux.", createdAt: '2026-07-14T09:14:00.000Z' },
      { id: 'tl-j3', type: 'ai_reply', title: 'AI Replied', description: 'Sarah shared Hilux 2.4 GD-6 Raider pricing from R549,900.', createdAt: '2026-07-14T09:14:30.000Z' },
      { id: 'tl-j4', type: 'knowledge', title: 'Knowledge Used', description: 'Vehicle Catalogue 2025, Finance Terms', createdAt: '2026-07-14T09:14:30.000Z' },
      { id: 'tl-j10', type: 'whatsapp', title: 'WhatsApp Message', description: "I'm looking for a Toyota Hilux.", createdAt: '2026-07-20T14:30:00.000Z' },
    ],
    analytics: { messages: 24, aiReplies: 18, humanReplies: 0, avgResponseTimeMs: 1180, topTopic: 'Vehicle Finance', ltv: 0, purchaseProbability: 87 },
    messages: [
      { id: 'm-j1', role: 'customer', message: 'Hello', time: '09:14' },
      { id: 'm-j2', role: 'ai', message: 'Hello John. How may I help you today?', time: '09:14' },
      { id: 'm-j3', role: 'customer', message: "I'm looking for a Toyota Hilux.", time: '09:15' },
    ],
    lastSeen: '2026-07-20T14:32:00.000Z',
    lastMessage: "I'm looking for a Toyota Hilux.",
  },
  {
    id: '27834445566',
    phone: '27834445566',
    phoneDisplay: '+27 83 444 5566',
    name: 'Sarah Jones',
    email: 'sarah.j@outlook.com',
    companyId: 'demo-central-motors',
    companyName: 'Central Motors',
    status: 'in_progress',
    online: false,
    customerSince: '2025-03-10T08:00:00.000Z',
    leadScore: 74,
    averageSentiment: 'positive',
    sentimentLabel: 'Positive',
    aiConfidence: 91,
    assignedAiEmployee: 'Sarah',
    tags: ['Sales', 'VIP'],
    aiSummary: 'Repeat Central Motors customer (Corolla owner). Wants to book a test drive — likely upsell to newer model.',
    recommendedAction: { action: 'Confirm test drive slot for preferred model', reason: 'Customer explicitly asked to book a test drive.', confidence: 89 },
    notesList: [{ id: 'note-s1', text: 'Repeat customer — owns Corolla. Upsell to new model.', author: 'Sarah (AI)', createdAt: '2026-07-20T08:55:00.000Z' }],
    tasks: [],
    documents: [],
    orders: [{ id: 'ord-s1', label: 'Service — Corolla', status: 'completed', amount: 2499, date: '2025-03-15' }],
    timeline: [{ id: 'tl-s3', type: 'whatsapp', title: 'WhatsApp Message', description: 'Can you help me book a test drive?', createdAt: '2026-07-20T08:54:00.000Z' }],
    analytics: { messages: 12, aiReplies: 9, humanReplies: 0, avgResponseTimeMs: 1320, topTopic: 'Test Drive', ltv: 2499, purchaseProbability: 62 },
    messages: demoInboxMessages('conv-sarah-jones'),
    lastSeen: '2026-07-20T08:54:00.000Z',
    lastMessage: 'Can you help me book a test drive?',
  },
  {
    id: '27718889900',
    phone: '27718889900',
    phoneDisplay: '+27 71 888 9900',
    name: 'David Nkosi',
    email: 'david.nkosi@yahoo.com',
    companyId: 'demo-central-motors',
    companyName: 'Central Motors',
    status: 'human_takeover',
    online: false,
    customerSince: '2026-07-18T08:00:00.000Z',
    leadScore: 68,
    averageSentiment: 'neutral',
    sentimentLabel: 'Neutral',
    aiConfidence: 72,
    assignedAiEmployee: 'Sarah',
    assignedHumanAgent: 'Sarah',
    tags: ['Sales', 'Hot Lead'],
    aiSummary: 'David Nkosi applying for vehicle finance. Human agent Sarah handling deposit questions.',
    recommendedAction: { action: 'Human finance consultant to call with deposit breakdown', reason: 'Finance application in progress.', confidence: 82 },
    notesList: [{ id: 'note-d1', text: 'Customer wants financing. Call tomorrow.', author: 'Sarah', createdAt: '2026-07-20T08:35:00.000Z' }],
    tasks: [{ id: 'task-d1', title: 'Call David with finance quote', deadline: '2026-07-21T10:00:00.000Z', priority: 'high', assignedTo: 'Sarah', done: false, createdAt: '2026-07-20T08:36:00.000Z' }],
    documents: [],
    orders: [],
    timeline: [{ id: 'tl-d3', type: 'human_takeover', title: 'Human Took Over', description: 'Sarah joined conversation for finance consultation.', createdAt: '2026-07-20T08:35:00.000Z' }],
    analytics: { messages: 8, aiReplies: 4, humanReplies: 2, avgResponseTimeMs: 2100, topTopic: 'Finance', ltv: 0, purchaseProbability: 55 },
    messages: demoInboxMessages('conv-david-finance'),
    lastSeen: '2026-07-20T08:32:00.000Z',
    lastMessage: 'Finance application — what deposit do I need?',
  },
  {
    id: '27842223344',
    phone: '27842223344',
    phoneDisplay: '+27 84 222 3344',
    name: 'Peter Molefe',
    email: '',
    companyId: 'demo-econo-funerals',
    companyName: 'Econo Funerals',
    status: 'in_progress',
    online: false,
    customerSince: '2026-07-20T07:45:00.000Z',
    leadScore: 90,
    averageSentiment: 'positive',
    sentimentLabel: 'Positive',
    aiConfidence: 88,
    assignedAiEmployee: 'Grace',
    tags: ['Support', 'Hot Lead'],
    aiSummary: 'Peter Molefe enquiring about funeral packages for his father. Sensitive, high-urgency lead.',
    recommendedAction: { action: 'Offer compassionate package breakdown and family liaison callback', reason: 'High urgency bereavement enquiry.', confidence: 91 },
    notesList: [],
    tasks: [],
    documents: [],
    orders: [],
    timeline: [{ id: 'tl-p2', type: 'whatsapp', title: 'WhatsApp Message', description: 'Funeral packages for my father', createdAt: '2026-07-20T07:48:00.000Z' }],
    analytics: { messages: 3, aiReplies: 2, humanReplies: 0, avgResponseTimeMs: 980, topTopic: 'Funeral Packages', ltv: 0, purchaseProbability: 78 },
    messages: demoInboxMessages('conv-peter-funerals'),
    lastSeen: '2026-07-20T07:48:00.000Z',
    lastMessage: 'Funeral packages for my father',
  },
];

export function normalizeCustomerPhone(phone) {
  return String(phone || '').replace(/\D/g, '');
}

export function filterDemoCustomers(companyId) {
  if (!companyId) return [...DEMO_CUSTOMERS];
  return DEMO_CUSTOMERS.filter((c) => c.companyId === companyId);
}

export function getDemoCustomer(phoneOrId) {
  const key = normalizeCustomerPhone(phoneOrId);
  return DEMO_CUSTOMERS.find((c) => normalizeCustomerPhone(c.phone) === key || c.id === phoneOrId) || null;
}

export function getDemoCustomerListRows(companyId) {
  return filterDemoCustomers(companyId).map((c) => ({
    id: c.id,
    phone: c.phone,
    name: c.name,
    email: c.email,
    companyId: c.companyId,
    companyName: c.companyName,
    leadScore: c.leadScore,
    averageSentiment: c.averageSentiment,
    sentimentLabel: c.sentimentLabel,
    lastSeen: c.lastSeen,
    tags: c.tags,
    status: c.status,
    online: c.online,
    assignedAiEmployee: c.assignedAiEmployee,
    lastMessage: c.lastMessage,
  }));
}

/* ── Workflow Automation Studio — demo data ── */

const wfNode = (id, type, stepType, label, icon, config = {}, branch = null) => ({
  id, type, stepType, label, icon, config, ...(branch ? { branch } : {}),
});

const financeNodes = [
  wfNode('n1', 'trigger', 'whatsapp_message', 'WhatsApp Message', 'fa-brands fa-whatsapp'),
  wfNode('n2', 'condition', 'contains_keyword', 'Contains "finance"', 'fa-solid fa-filter', { keyword: 'finance' }),
  wfNode('n3', 'ai_action', 'generate_proposal', 'AI Generate Proposal', 'fa-solid fa-wand-magic-sparkles', { template: 'vehicle_finance' }),
  wfNode('n4', 'action', 'create_task', 'Create CRM Task', 'fa-solid fa-list-check', { title: 'Finance enquiry follow-up', priority: 'high' }),
  wfNode('n5', 'action', 'assign_human', 'Assign Sales', 'fa-solid fa-user-tie', { department: 'Sales' }),
  wfNode('n6', 'action', 'delay', 'Follow up 24h', 'fa-solid fa-clock', { hours: 24 }),
];

const testDriveNodes = [
  wfNode('n1', 'trigger', 'whatsapp_message', 'WhatsApp Message', 'fa-brands fa-whatsapp'),
  wfNode('n2', 'condition', 'contains_keyword', 'Contains "test drive"', 'fa-solid fa-filter', { keyword: 'test drive' }),
  wfNode('n3', 'condition', 'business_hours', 'Business Hours', 'fa-solid fa-clock', { start: '08:00', end: '17:00' }),
  wfNode('n4', 'ai_action', 'extract_entities', 'Extract Vehicle & Date', 'fa-solid fa-tags', { entities: ['vehicle', 'date'] }),
  wfNode('n5', 'action', 'reply', 'Send Booking Confirmation', 'fa-solid fa-reply', { template: 'test_drive_confirmation' }),
  wfNode('n6', 'action', 'update_crm', 'Update CRM Lead', 'fa-solid fa-address-book', { stage: 'test_drive_scheduled' }),
];

const serviceNodes = [
  wfNode('n1', 'trigger', 'scheduled', 'Scheduled Trigger', 'fa-solid fa-calendar-days', { cron: '0 9 * * 1' }),
  wfNode('n2', 'condition', 'lead_score', 'Due for Service', 'fa-solid fa-gauge-high', { field: 'daysSinceService', operator: 'gte', value: 180 }),
  wfNode('n3', 'action', 'reply', 'WhatsApp Reminder', 'fa-solid fa-reply', { template: 'service_reminder' }),
  wfNode('n4', 'action', 'create_task', 'Create Service Task', 'fa-solid fa-list-check', { title: 'Service booking outreach' }),
];

export const DEMO_WORKFLOWS = [
  {
    id: 'demo-wf-finance-enquiry',
    name: 'Finance Enquiry',
    companyId: 'demo-central-motors',
    companyName: 'Central Motors',
    status: 'published',
    currentVersion: 3,
    createdAt: '2025-07-01T08:00:00.000Z',
    updatedAt: '2025-07-15T14:30:00.000Z',
    createdBy: 'John Smith',
    nodes: JSON.parse(JSON.stringify(financeNodes)),
    publishedNodes: JSON.parse(JSON.stringify(financeNodes)),
    versions: [
      { version: 1, nodes: financeNodes.slice(0, 4), createdAt: '2025-07-01T08:00:00.000Z', publishedAt: '2025-07-01T09:00:00.000Z', createdBy: 'John Smith' },
      { version: 2, nodes: financeNodes.slice(0, 5), createdAt: '2025-07-08T10:00:00.000Z', publishedAt: '2025-07-08T11:00:00.000Z', createdBy: 'Sarah van Wyk' },
      { version: 3, nodes: financeNodes, createdAt: '2025-07-15T14:00:00.000Z', publishedAt: '2025-07-15T14:30:00.000Z', createdBy: 'John Smith' },
    ],
  },
  {
    id: 'demo-wf-test-drive',
    name: 'Test Drive Booking',
    companyId: 'demo-central-motors',
    companyName: 'Central Motors',
    status: 'published',
    currentVersion: 2,
    createdAt: '2025-06-20T09:00:00.000Z',
    updatedAt: '2025-07-10T16:00:00.000Z',
    createdBy: 'Sarah van Wyk',
    nodes: JSON.parse(JSON.stringify(testDriveNodes)),
    publishedNodes: JSON.parse(JSON.stringify(testDriveNodes)),
    versions: [
      { version: 1, nodes: testDriveNodes.slice(0, 4), createdAt: '2025-06-20T09:00:00.000Z', publishedAt: '2025-06-21T08:00:00.000Z', createdBy: 'Sarah van Wyk' },
      { version: 2, nodes: testDriveNodes, createdAt: '2025-07-10T15:30:00.000Z', publishedAt: '2025-07-10T16:00:00.000Z', createdBy: 'Sarah van Wyk' },
    ],
  },
  {
    id: 'demo-wf-service-reminder',
    name: 'Service Reminder',
    companyId: 'demo-central-motors',
    companyName: 'Central Motors',
    status: 'draft',
    currentVersion: 1,
    createdAt: '2025-07-16T11:00:00.000Z',
    updatedAt: '2025-07-17T09:00:00.000Z',
    createdBy: 'John Smith',
    nodes: JSON.parse(JSON.stringify(serviceNodes)),
    publishedNodes: [],
    versions: [],
  },
];

export const DEMO_TEMPLATES = [
  { id: 'tpl-automotive-finance-enquiry', name: 'Finance Enquiry', industry: 'Automotive', category: 'automotive', description: 'Qualify finance leads via WhatsApp, generate AI proposal, create CRM task, and assign sales with 24h follow-up.', icon: 'fa-solid fa-hand-holding-dollar', companyHint: 'Central Motors', stepCount: 6 },
  { id: 'tpl-automotive-test-drive', name: 'Test Drive Booking', industry: 'Automotive', category: 'automotive', description: 'Capture test drive requests, check business hours, book slot, and confirm via WhatsApp.', icon: 'fa-solid fa-car', stepCount: 6 },
  { id: 'tpl-automotive-service-reminder', name: 'Service Reminder', industry: 'Automotive', category: 'automotive', description: 'Scheduled reminder for upcoming service appointments with WhatsApp nudge.', icon: 'fa-solid fa-wrench', stepCount: 4 },
  { id: 'tpl-schools-admission', name: 'Admission Enquiry', industry: 'Schools', category: 'schools', description: 'Handle admission questions, classify intent, and route to admissions team.', icon: 'fa-solid fa-graduation-cap', stepCount: 5 },
  { id: 'tpl-schools-fee-reminder', name: 'Fee Reminder', industry: 'Schools', category: 'schools', description: 'Payment received trigger with overdue fee follow-up workflow.', icon: 'fa-solid fa-money-bill-wave', stepCount: 5 },
  { id: 'tpl-funeral-booking', name: 'Funeral Booking', industry: 'Funeral', category: 'funeral', description: 'Sensitive intake for funeral arrangements with human escalation.', icon: 'fa-solid fa-heart', stepCount: 5 },
  { id: 'tpl-funeral-claims', name: 'Claims Assistance', industry: 'Funeral', category: 'funeral', description: 'Guide families through insurance and policy claims documentation.', icon: 'fa-solid fa-file-contract', stepCount: 5 },
  { id: 'tpl-law-consultation', name: 'Consultation Booking', industry: 'Law', category: 'law', description: 'Book legal consultations and capture matter type.', icon: 'fa-solid fa-scale-balanced', stepCount: 5 },
  { id: 'tpl-law-case-intake', name: 'Case Intake', industry: 'Law', category: 'law', description: 'Structured case intake with AI confidence gate before human review.', icon: 'fa-solid fa-folder-open', stepCount: 5 },
  { id: 'tpl-churches-prayer', name: 'Prayer Requests', industry: 'Churches', category: 'churches', description: 'Collect prayer requests with pastoral team notification.', icon: 'fa-solid fa-hands-praying', stepCount: 5 },
  { id: 'tpl-churches-donations', name: 'Donations', industry: 'Churches', category: 'churches', description: 'Handle donation enquiries and send payment links.', icon: 'fa-solid fa-hand-holding-heart', stepCount: 5 },
];
