/**
 * Seed rich CRM profiles into memory storage when empty (STORAGE_BACKEND=memory).
 */

const ts = (date, time = "10:00:00") => `${date}T${time}.000Z`;

export function buildDemoCustomers() {
    const johnPhone = "27849000523";
    const sarahPhone = "27834445566";
    const davidPhone = "27718889900";
    const peterPhone = "27842223344";

    return [
        {
            phone: johnPhone,
            id: johnPhone,
            name: "John Smith",
            email: "johndoe@email.com",
            companyId: "demo-central-motors",
            companyName: "Central Motors",
            channel: "whatsapp",
            status: "in_progress",
            mode: "ai",
            online: true,
            customerSince: ts("2026-07-14", "09:00:00"),
            createdAt: ts("2026-07-14", "09:00:00"),
            lastSeen: ts("2026-07-20", "14:32:00"),
            tags: ["VIP", "Hot Lead", "Finance"],
            leadScore: 92,
            leadScoreBreakdown: {
                conversationFrequency: 18,
                questionsAsked: 16,
                productsViewed: 15,
                positiveSentiment: 14,
                purchaseIntent: 17,
                responseSpeed: 12,
            },
            averageSentiment: "positive",
            sentimentLabel: "Positive",
            aiConfidence: 98,
            assignedAiEmployee: "Sarah",
            assignedEmployee: null,
            assignedHumanAgent: null,
            aiSummary:
                "John Smith is a high-intent buyer at Central Motors interested in a white Toyota Hilux Double Cab within a R450,000 budget. He has asked about vehicle finance three times, mentioned a trade-in on his 2019 Ford Ranger, and prefers white exterior with black interior. Sarah (AI) has shared Hilux specs, finance terms, and trade-in valuation info. Recommended next step: send finance application link and book test drive.",
            recommendedAction: {
                action: "Offer finance application link and schedule Hilux test drive",
                reason: "Customer has asked about financing three times and confirmed budget + trade-in.",
                confidence: 96,
            },
            interests: {
                vehicle: "Toyota Hilux 2.4 GD-6 Double Cab",
                color: "White",
                budget: "R450,000",
                finance: true,
                tradeIn: "2019 Ford Ranger",
            },
            notesList: [
                {
                    id: "note-j1",
                    text: "Repeat enquiry — previously visited showroom in June. Very motivated buyer.",
                    author: "Sarah (AI)",
                    createdAt: ts("2026-07-15", "11:20:00"),
                },
                {
                    id: "note-j2",
                    text: "Finance pre-check requested. Minimum 10% deposit confirmed. Trade-in valuation pending photos.",
                    author: "John Smith (Sales)",
                    createdAt: ts("2026-07-18", "09:45:00"),
                },
            ],
            tasks: [
                {
                    id: "task-j1",
                    title: "Call customer re: finance application",
                    deadline: ts("2026-07-21", "17:00:00"),
                    priority: "high",
                    assignedTo: "Sarah",
                    done: false,
                    createdAt: ts("2026-07-19", "08:00:00"),
                },
                {
                    id: "task-j2",
                    title: "Book Hilux test drive — white model",
                    deadline: ts("2026-07-22", "12:00:00"),
                    priority: "medium",
                    assignedTo: "Unassigned",
                    done: false,
                    createdAt: ts("2026-07-20", "10:15:00"),
                },
            ],
            documents: [
                { id: "doc-j1", name: "Trade-in photos — Ranger", type: "image", uploadedAt: ts("2026-07-17", "15:30:00") },
                { id: "doc-j2", name: "ID copy — John Smith.pdf", type: "pdf", uploadedAt: ts("2026-07-18", "09:00:00") },
            ],
            orders: [
                {
                    id: "ord-j0",
                    label: "No completed purchase yet",
                    status: "pending",
                    amount: null,
                    date: null,
                },
            ],
            timeline: [
                { id: "tl-j1", type: "created", title: "Customer Created", description: "Profile created from WhatsApp inbound.", createdAt: ts("2026-07-14", "09:00:00") },
                { id: "tl-j2", type: "whatsapp", title: "WhatsApp Message", description: "Hello — I'm looking for a Toyota Hilux.", createdAt: ts("2026-07-14", "09:14:00") },
                { id: "tl-j3", type: "ai_reply", title: "AI Replied", description: "Sarah shared Hilux 2.4 GD-6 Raider pricing from R549,900.", createdAt: ts("2026-07-14", "09:14:30") },
                { id: "tl-j4", type: "knowledge", title: "Knowledge Used", description: "Vehicle Catalogue 2025, Finance Terms", createdAt: ts("2026-07-14", "09:14:30"), meta: { sources: ["Vehicle Catalogue 2025", "Finance Terms"] } },
                { id: "tl-j5", type: "whatsapp", title: "WhatsApp Message", description: "What's my budget for finance on a white Hilux? Around R450k.", createdAt: ts("2026-07-15", "10:22:00") },
                { id: "tl-j6", type: "ai_reply", title: "AI Replied", description: "Explained 10% deposit, partner banks, balloon options.", createdAt: ts("2026-07-15", "10:22:45") },
                { id: "tl-j7", type: "whatsapp", title: "WhatsApp Message", description: "Can I trade in my 2019 Ford Ranger?", createdAt: ts("2026-07-16", "14:05:00") },
                { id: "tl-j8", type: "knowledge", title: "Knowledge Used", description: "Trade-In Valuation FAQ", createdAt: ts("2026-07-16", "14:05:30") },
                { id: "tl-j9", type: "follow_up", title: "Follow-up Reminder", description: "Send finance application link — customer asked 3× about financing.", createdAt: ts("2026-07-19", "08:00:00") },
                { id: "tl-j10", type: "whatsapp", title: "WhatsApp Message", description: "I'm looking for a Toyota Hilux.", createdAt: ts("2026-07-20", "14:30:00") },
            ],
            analytics: {
                messages: 24,
                aiReplies: 18,
                humanReplies: 0,
                avgResponseTimeMs: 1180,
                lastSeen: ts("2026-07-20", "14:32:00"),
                topTopic: "Vehicle Finance",
                ltv: 0,
                purchaseProbability: 87,
            },
            totalMessages: 24,
            totalConversations: 3,
            lastMessage: "I'm looking for a Toyota Hilux.",
            lifetimeValue: null,
            lastPurchase: null,
        },
        {
            phone: sarahPhone,
            id: sarahPhone,
            name: "Sarah Jones",
            email: "sarah.j@outlook.com",
            companyId: "demo-central-motors",
            companyName: "Central Motors",
            channel: "whatsapp",
            status: "in_progress",
            mode: "ai",
            online: false,
            customerSince: ts("2025-03-10", "08:00:00"),
            createdAt: ts("2025-03-10", "08:00:00"),
            lastSeen: ts("2026-07-20", "08:54:00"),
            tags: ["Sales", "VIP"],
            leadScore: 74,
            leadScoreBreakdown: {
                conversationFrequency: 14,
                questionsAsked: 12,
                productsViewed: 10,
                positiveSentiment: 13,
                purchaseIntent: 12,
                responseSpeed: 13,
            },
            averageSentiment: "positive",
            sentimentLabel: "Positive",
            aiConfidence: 91,
            assignedAiEmployee: "Sarah",
            assignedEmployee: null,
            aiSummary:
                "Repeat Central Motors customer (Corolla owner, Mar 2025 service). Sarah Jones wants to book a test drive — likely upsell to newer model. Friendly tone, high trust.",
            recommendedAction: {
                action: "Confirm test drive slot for preferred model",
                reason: "Customer explicitly asked to book a test drive.",
                confidence: 89,
            },
            notesList: [{ id: "note-s1", text: "Repeat customer — owns Corolla. Upsell to new model.", author: "Sarah (AI)", createdAt: ts("2026-07-20", "08:55:00") }],
            tasks: [],
            documents: [],
            orders: [{ id: "ord-s1", label: "Service — Corolla", status: "completed", amount: 2499, date: ts("2025-03-15") }],
            timeline: [
                { id: "tl-s1", type: "created", title: "Customer Created", description: "Existing customer synced from CRM.", createdAt: ts("2025-03-10", "08:00:00") },
                { id: "tl-s2", type: "purchase", title: "Purchase", description: "Corolla service — R2,499", createdAt: ts("2025-03-15", "11:00:00") },
                { id: "tl-s3", type: "whatsapp", title: "WhatsApp Message", description: "Can you help me book a test drive?", createdAt: ts("2026-07-20", "08:54:00") },
                { id: "tl-s4", type: "ai_reply", title: "AI Replied", description: "Offered Mon–Sat test drive slots.", createdAt: ts("2026-07-20", "08:54:30") },
            ],
            analytics: { messages: 12, aiReplies: 9, humanReplies: 0, avgResponseTimeMs: 1320, topTopic: "Test Drive", ltv: 2499, purchaseProbability: 62 },
            totalMessages: 12,
            totalConversations: 7,
            lastMessage: "Can you help me book a test drive?",
            lifetimeValue: 2499,
            lastPurchase: "R2,499 service (Mar 2025)",
        },
        {
            phone: davidPhone,
            id: davidPhone,
            name: "David Nkosi",
            email: "david.nkosi@yahoo.com",
            companyId: "demo-central-motors",
            companyName: "Central Motors",
            channel: "whatsapp",
            status: "human_takeover",
            mode: "human",
            online: false,
            customerSince: ts("2026-07-18", "08:00:00"),
            createdAt: ts("2026-07-18", "08:00:00"),
            lastSeen: ts("2026-07-20", "08:32:00"),
            tags: ["Sales", "Hot Lead"],
            leadScore: 68,
            leadScoreBreakdown: {
                conversationFrequency: 10,
                questionsAsked: 14,
                productsViewed: 8,
                positiveSentiment: 11,
                purchaseIntent: 13,
                responseSpeed: 12,
            },
            averageSentiment: "neutral",
            sentimentLabel: "Neutral",
            aiConfidence: 72,
            assignedAiEmployee: "Sarah",
            assignedEmployee: "Sarah",
            assignedHumanAgent: "Sarah",
            aiSummary:
                "David Nkosi is applying for vehicle finance on a new vehicle. Minimum deposit questions escalated to human agent Sarah. Follow up with personalised finance quote.",
            recommendedAction: {
                action: "Human finance consultant to call with deposit breakdown",
                reason: "Finance application in progress; human takeover active.",
                confidence: 82,
            },
            notesList: [{ id: "note-d1", text: "Customer wants financing. Call tomorrow.", author: "Sarah", createdAt: ts("2026-07-20", "08:35:00") }],
            tasks: [{ id: "task-d1", title: "Call David with finance quote", deadline: ts("2026-07-21", "10:00:00"), priority: "high", assignedTo: "Sarah", done: false, createdAt: ts("2026-07-20", "08:36:00") }],
            documents: [],
            orders: [],
            timeline: [
                { id: "tl-d1", type: "created", title: "Customer Created", description: "New lead from WhatsApp.", createdAt: ts("2026-07-18", "08:00:00") },
                { id: "tl-d2", type: "whatsapp", title: "WhatsApp Message", description: "Finance application — what deposit do I need?", createdAt: ts("2026-07-20", "08:32:00") },
                { id: "tl-d3", type: "human_takeover", title: "Human Took Over", description: "Sarah joined conversation for finance consultation.", createdAt: ts("2026-07-20", "08:35:00") },
            ],
            analytics: { messages: 8, aiReplies: 4, humanReplies: 2, avgResponseTimeMs: 2100, topTopic: "Finance", ltv: 0, purchaseProbability: 55 },
            totalMessages: 8,
            totalConversations: 2,
            lastMessage: "Finance application — what deposit do I need?",
            lifetimeValue: null,
            lastPurchase: null,
        },
        {
            phone: peterPhone,
            id: peterPhone,
            name: "Peter Molefe",
            email: "",
            companyId: "demo-econo-funerals",
            companyName: "Econo Funerals",
            channel: "whatsapp",
            status: "in_progress",
            mode: "ai",
            online: false,
            customerSince: ts("2026-07-20", "07:45:00"),
            createdAt: ts("2026-07-20", "07:45:00"),
            lastSeen: ts("2026-07-20", "07:48:00"),
            tags: ["Support", "Hot Lead"],
            leadScore: 90,
            leadScoreBreakdown: {
                conversationFrequency: 8,
                questionsAsked: 10,
                productsViewed: 12,
                positiveSentiment: 15,
                purchaseIntent: 16,
                responseSpeed: 14,
            },
            averageSentiment: "positive",
            sentimentLabel: "Positive",
            aiConfidence: 88,
            assignedAiEmployee: "Grace",
            assignedEmployee: null,
            aiSummary:
                "Peter Molefe enquiring about funeral packages for his father. Sensitive, high-urgency lead. Grace (AI) offered Basic, Standard, and Premium package breakdown.",
            recommendedAction: {
                action: "Offer compassionate package breakdown and family liaison callback",
                reason: "High urgency bereavement enquiry with strong purchase intent.",
                confidence: 91,
            },
            notesList: [],
            tasks: [],
            documents: [],
            orders: [],
            timeline: [
                { id: "tl-p1", type: "created", title: "Customer Created", description: "WhatsApp inbound — Econo Funerals.", createdAt: ts("2026-07-20", "07:45:00") },
                { id: "tl-p2", type: "whatsapp", title: "WhatsApp Message", description: "Funeral packages for my father", createdAt: ts("2026-07-20", "07:48:00") },
                { id: "tl-p3", type: "ai_reply", title: "AI Replied", description: "Grace shared package options from R8,500.", createdAt: ts("2026-07-20", "07:48:30") },
                { id: "tl-p4", type: "knowledge", title: "Knowledge Used", description: "Econo Funerals Services", createdAt: ts("2026-07-20", "07:48:30") },
            ],
            analytics: { messages: 3, aiReplies: 2, humanReplies: 0, avgResponseTimeMs: 980, topTopic: "Funeral Packages", ltv: 0, purchaseProbability: 78 },
            totalMessages: 3,
            totalConversations: 1,
            lastMessage: "Funeral packages for my father",
            lifetimeValue: null,
            lastPurchase: null,
        },
    ];
}

export async function seedDemoCustomersIfEmpty(adapter) {
    if (!adapter?.listCustomers) return;
    const existing = await adapter.listCustomers({ limit: 1 });
    if (existing.length > 0) return;

    const demos = buildDemoCustomers();
    for (const customer of demos) {
        await adapter.upsertCustomer(customer.phone, customer);
    }
    console.log("[seed] Loaded", demos.length, "demo CRM customers into memory storage");
}
