/**
 * Browser build of billing plans — AUTO-GENERATED by prepare-sites from services/platform/billingPlans.js
 * Do not edit by hand; run: node scripts/prepare-sites.js
 */
(function (global) {
    'use strict';

    const FALLBACK_PLANS = [
    {
        "id": "trial",
        "label": "Trial",
        "price": 0,
        "currency": "ZAR",
        "billingCycle": "monthly",
        "trialDays": 14,
        "tagline": "14-day free trial",
        "features": [
            "1 AI Employee",
            "100 conversations",
            "1 team member",
            "500 MB storage"
        ],
        "limits": {
            "aiEmployees": 1,
            "conversations": 100,
            "messages": 500,
            "tokens": 50000,
            "users": 1,
            "storageMb": 512,
            "workflows": 2,
            "knowledgeDocs": 10,
            "workflowRuns": 50,
            "apiCalls": 1000,
            "knowledgeSizeMb": 50
        }
    },
    {
        "id": "starter",
        "label": "Starter",
        "headline": "Start with Sarah",
        "description": "For businesses ready to put AI to work on WhatsApp.",
        "price": 999.99,
        "currency": "ZAR",
        "billingCycle": "monthly",
        "tagline": "Start with Sarah",
        "features": [
            "Sarah AI Assistant",
            "WhatsApp",
            "3 business workspaces",
            "1,000 AI conversations / month",
            "CRM",
            "Knowledge Base",
            "Basic automation",
            "Sarah + 1 AI Employee"
        ],
        "limits": {
            "aiEmployees": 2,
            "conversations": 1000,
            "messages": 1000,
            "tokens": 100000,
            "users": 3,
            "workspaces": 3,
            "storageMb": 2048,
            "workflows": 5,
            "knowledgeDocs": 25,
            "workflowRuns": 200,
            "apiCalls": 5000,
            "knowledgeSizeMb": 200,
            "channels": [
                "whatsapp"
            ]
        }
    },
    {
        "id": "professional",
        "label": "Professional",
        "headline": "Connect your customers",
        "description": "For growing businesses communicating across multiple channels.",
        "price": 2999,
        "currency": "ZAR",
        "billingCycle": "monthly",
        "tagline": "Connect your customers",
        "featured": true,
        "features": [
            "Everything in Starter",
            "WhatsApp, Messenger & Email",
            "5 business workspaces",
            "5,000 AI conversations / month",
            "Advanced automation",
            "Sarah + 3 AI Employees",
            "Advanced analytics",
            "CRM & Knowledge Base"
        ],
        "limits": {
            "aiEmployees": 4,
            "conversations": 5000,
            "messages": 3000,
            "tokens": 250000,
            "users": 5,
            "workspaces": 5,
            "storageMb": 5120,
            "workflows": 20,
            "knowledgeDocs": 100,
            "workflowRuns": 1000,
            "apiCalls": 25000,
            "knowledgeSizeMb": 500,
            "channels": [
                "whatsapp",
                "messenger",
                "email"
            ]
        }
    },
    {
        "id": "business",
        "label": "Business",
        "headline": "Run your business everywhere",
        "description": "For businesses ready to operate AI across every major customer channel.",
        "price": 4999,
        "currency": "ZAR",
        "billingCycle": "monthly",
        "tagline": "Run your business everywhere",
        "features": [
            "Everything in Professional",
            "WhatsApp, Messenger, Email, Instagram & Webchat",
            "10 business workspaces",
            "20,000 AI conversations / month",
            "Sarah + 10 AI Employees",
            "Advanced CRM",
            "Advanced automation",
            "Priority support"
        ],
        "limits": {
            "aiEmployees": 11,
            "conversations": 20000,
            "messages": 5000,
            "tokens": 500000,
            "users": 10,
            "workspaces": 10,
            "storageMb": 10240,
            "workflows": null,
            "knowledgeDocs": null,
            "workflowRuns": null,
            "apiCalls": 50000,
            "knowledgeSizeMb": null,
            "channels": [
                "whatsapp",
                "messenger",
                "email",
                "instagram",
                "webchat"
            ]
        }
    },
    {
        "id": "enterprise",
        "label": "Enterprise",
        "headline": "Build your AI workforce",
        "description": "For organisations that want ZiricAI across their entire operation.",
        "price": null,
        "currency": "ZAR",
        "billingCycle": "monthly",
        "contactSales": true,
        "tagline": "Build your AI workforce",
        "features": [
            "Everything in Business",
            "All channels",
            "Unlimited workspaces",
            "Custom AI conversations",
            "Unlimited / custom AI Employees",
            "Mission Control",
            "Custom integrations",
            "Enterprise security & dedicated support"
        ],
        "limits": {
            "aiEmployees": null,
            "conversations": null,
            "messages": null,
            "tokens": null,
            "users": null,
            "workspaces": null,
            "storageMb": null,
            "workflows": null,
            "knowledgeDocs": null,
            "workflowRuns": null,
            "apiCalls": null,
            "knowledgeSizeMb": null,
            "channels": null
        }
    }
];

    const PUBLIC_PLAN_IDS = ["starter","professional","business","enterprise"];

    let plans = FALLBACK_PLANS.slice();

    function getPlan(planId) {
        return plans.find((p) => p.id === planId) || plans.find((p) => p.id === 'trial') || FALLBACK_PLANS[0];
    }

    function getAllPlans() {
        return plans.slice();
    }

    function getPublicPlans() {
        return PUBLIC_PLAN_IDS.map((id) => getPlan(id));
    }

    function formatPrice(amount, currency, opts) {
        const suffix = (opts && opts.suffix) || '';
        if (amount == null) return 'Custom';
        if (Number(amount) === 0) return 'Free';
        const prefix = (currency || 'ZAR') === 'ZAR' ? 'R' : `${currency} `;
        const num = Number(amount);
        let formatted;
        if (Number.isInteger(num)) {
            formatted = num.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',');
        } else {
            const parts = num.toFixed(2).split('.');
            formatted = `${parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, ',')}.${parts[1]}`;
        }
        return `${prefix}${formatted}${suffix}`;
    }

    function getMinimumPlanPrice() {
        return getPlan('starter').price;
    }

    function formatPlanPriceLine(plan) {
        if (plan.price == null || plan.contactSales) {
            return `${plan.label} Custom pricing`;
        }
        return `${plan.label} ${formatPrice(plan.price)}/month`;
    }

    function getPricingSummaryText() {
        const planLines = getPublicPlans().map((plan) => {
            const pitch = plan.headline || plan.tagline || (plan.features && plan.features[0]) || plan.label;
            return `${formatPlanPriceLine(plan)} — ${pitch}`;
        });
        return (
            `Plans: ${planLines.join('; ')}. ` +
            'Start with Sarah on WhatsApp, then add Messenger, email, Instagram, and webchat as you grow. ' +
            'Every plan includes CRM, knowledge, automation, and a 14-day free trial.'
        );
    }

    function getDefaultPlatformReply() {
        return (
            'ZiricAI starts with Sarah on WhatsApp — then you add channels and AI Employees as your business grows. ' +
            `Plans start at ${formatPrice(getMinimumPlanPrice())}/month with a 14-day free trial. ` +
            'Ask about channels, workspaces, conversations included, CRM, automation, or upgrading from Starter to Professional.'
        );
    }

    function setPlans(nextPlans) {
        if (Array.isArray(nextPlans) && nextPlans.length) {
            plans = nextPlans;
        }
    }

    async function refreshFromApi() {
        try {
            const res = await fetch('/api/billing/plans', { headers: { Accept: 'application/json' } });
            if (!res.ok) return false;
            const data = await res.json();
            if (Array.isArray(data.plans) && data.plans.length && data.plans.some((p) => p.headline)) {
                setPlans(data.plans);
                return true;
            }
        } catch {
            /* static hosting or offline — keep fallback */
        }
        return false;
    }

    global.ZiricBillingPlans = {
        getPlan,
        getAllPlans,
        getPublicPlans,
        formatPrice,
        getMinimumPlanPrice,
        getPricingSummaryText,
        getDefaultPlatformReply,
        refreshFromApi,
        PUBLIC_PLAN_IDS,
    };

    refreshFromApi();
})(typeof window !== 'undefined' ? window : globalThis);
