/**
 * AI Employees catalog — single source of truth for landing hire sections.
 * Integrates with marketplacePacks.js where packId matches.
 */

export const DEPARTMENTS = {
    administration: { id: "administration", label: "Administration", icon: "📋" },
    sales: { id: "sales", label: "Sales", icon: "💼" },
    marketing: { id: "marketing", label: "Marketing", icon: "📈" },
    hr: { id: "hr", label: "Human Resources", icon: "👥" },
    finance: { id: "finance", label: "Finance", icon: "💰" },
    legal: { id: "legal", label: "Legal", icon: "⚖️" },
    healthcare: { id: "healthcare", label: "Healthcare", icon: "🏥" },
    education: { id: "education", label: "Education", icon: "🎓" },
    support: { id: "support", label: "Customer Support", icon: "🎧" },
    operations: { id: "operations", label: "Operations", icon: "⚙️" },
    hospitality: { id: "hospitality", label: "Hospitality", icon: "🏨" },
    faith: { id: "faith", label: "Faith & Community", icon: "⛪" },
};

/** Department role listings for the Hire AI Employees section */
export const DEPARTMENT_ROLES = [
    {
        department: "administration",
        roles: ["AI Receptionist", "Office Administrator", "Executive Assistant"],
    },
    {
        department: "sales",
        roles: ["Sales Rep", "Lead Qualification", "Account Manager"],
    },
    {
        department: "marketing",
        roles: ["Marketing Manager", "Social Media", "Content Creator"],
    },
    {
        department: "hr",
        roles: ["HR Officer", "Recruitment Officer", "Training Coordinator"],
    },
    {
        department: "finance",
        roles: ["Bookkeeper", "Accounts Assistant", "Payroll Officer"],
    },
    {
        department: "legal",
        roles: ["Legal Assistant", "Compliance Officer"],
    },
    {
        department: "healthcare",
        roles: ["Medical Receptionist", "Patient Support"],
    },
    {
        department: "education",
        roles: ["School Administrator", "Admissions Officer", "Parent Liaison"],
    },
];

/**
 * Full employee catalog — used for hire cards and catalog section.
 * monthlyPrice: number (ZAR), "included", or null (falls back to "Included in plan")
 */
export const AI_EMPLOYEES_CATALOG = [
    {
        id: "receptionist",
        title: "AI Receptionist",
        department: "administration",
        icon: "📞",
        shortDescription: "Answers calls and WhatsApp, books appointments, and greets every visitor — 24/7.",
        skills: ["Multi-channel reception", "Appointment scheduling", "Call routing", "Visitor management"],
        responsibilities: ["Answer inbound enquiries", "Book and confirm appointments", "Route urgent calls", "Capture visitor details"],
        languages: ["English", "Afrikaans", "Zulu", "Xhosa", "Sotho"],
        integrations: ["WhatsApp", "Google Calendar", "Microsoft 365", "CRM"],
        experienceLevel: "Entry",
        industries: ["automotive", "medical", "dentist", "legal", "retail", "hotel"],
        packId: "pack-appointment-ai",
        monthlyPrice: "included",
    },
    {
        id: "executive-assistant",
        title: "Executive Assistant",
        department: "administration",
        icon: "🧑‍💼",
        shortDescription: "Manages calendars, drafts correspondence, and keeps executives organised without the overhead.",
        skills: ["Calendar management", "Email triage", "Meeting prep", "Travel coordination"],
        responsibilities: ["Schedule meetings", "Draft and summarise emails", "Prepare briefing notes", "Coordinate travel"],
        languages: ["English", "Afrikaans"],
        integrations: ["Google Calendar", "Microsoft 365", "Slack", "Zoom"],
        experienceLevel: "Senior",
        industries: ["government", "accounting", "law-firm", "real-estate"],
        packId: null,
        monthlyPrice: "included",
    },
    {
        id: "sales-consultant",
        title: "Sales Consultant",
        department: "sales",
        icon: "💼",
        shortDescription: "Qualifies leads, answers product questions, and closes deals while your team sleeps.",
        skills: ["Lead qualification", "Product knowledge", "Quote generation", "Objection handling"],
        responsibilities: ["Qualify inbound leads", "Provide pricing and specs", "Schedule demos and test drives", "Follow up on quotes"],
        languages: ["English", "Afrikaans", "Zulu"],
        integrations: ["WhatsApp", "CRM", "Stripe", "Paystack"],
        experienceLevel: "Mid",
        industries: ["automotive", "retail", "real-estate", "insurance"],
        packId: "pack-sales-ai",
        monthlyPrice: "included",
    },
    {
        id: "customer-support",
        title: "Customer Support",
        department: "support",
        icon: "🎧",
        shortDescription: "Resolves issues, tracks orders, and keeps customers happy — before they churn.",
        skills: ["Ticket triage", "Order tracking", "Returns handling", "Escalation routing"],
        responsibilities: ["Answer support queries", "Track orders and deliveries", "Process returns", "Escalate complex issues"],
        languages: ["English", "Afrikaans", "Zulu", "Xhosa"],
        integrations: ["WhatsApp", "Email", "CRM", "Helpdesk"],
        experienceLevel: "Mid",
        industries: ["retail", "logistics", "courier", "restaurant"],
        packId: "pack-customer-support-ai",
        monthlyPrice: "included",
    },
    {
        id: "appointment-booking",
        title: "Appointment Booking",
        department: "operations",
        icon: "📅",
        shortDescription: "Books, reschedules, and confirms appointments across any calendar — zero double-bookings.",
        skills: ["Calendar sync", "Reminder automation", "Waitlist management", "Multi-location scheduling"],
        responsibilities: ["Book appointments", "Send confirmations and reminders", "Handle reschedules", "Manage waitlists"],
        languages: ["English", "Afrikaans", "Zulu"],
        integrations: ["Google Calendar", "Microsoft 365", "WhatsApp", "SMS"],
        experienceLevel: "Entry",
        industries: ["medical", "dentist", "beauty-salon", "gym", "automotive"],
        packId: "pack-appointment-ai",
        monthlyPrice: "included",
    },
    {
        id: "finance-assistant",
        title: "Finance Assistant",
        department: "finance",
        icon: "💰",
        shortDescription: "Handles invoicing queries, payment reminders, and account lookups automatically.",
        skills: ["Invoice management", "Payment follow-up", "Account lookups", "Expense categorisation"],
        responsibilities: ["Answer billing queries", "Send payment reminders", "Generate statements", "Track outstanding balances"],
        languages: ["English", "Afrikaans"],
        integrations: ["Stripe", "Paystack", "Xero", "QuickBooks"],
        experienceLevel: "Mid",
        industries: ["accounting", "retail", "construction", "insurance"],
        packId: "pack-collections-ai",
        monthlyPrice: "included",
    },
    {
        id: "crm-manager",
        title: "CRM Manager",
        department: "sales",
        icon: "📊",
        shortDescription: "Captures every lead, updates records, and keeps your pipeline moving without manual data entry.",
        skills: ["Lead capture", "Pipeline updates", "Contact enrichment", "Activity logging"],
        responsibilities: ["Log every conversation to CRM", "Update deal stages", "Enrich contact records", "Trigger follow-up workflows"],
        languages: ["English"],
        integrations: ["CRM", "WhatsApp", "Email", "Web forms"],
        experienceLevel: "Mid",
        industries: ["automotive", "real-estate", "recruitment", "insurance"],
        packId: "pack-sales-ai",
        monthlyPrice: "included",
    },
    {
        id: "marketing-assistant",
        title: "Marketing Assistant",
        department: "marketing",
        icon: "📈",
        shortDescription: "Turns enquiries into campaigns, drafts content, and manages social responses.",
        skills: ["Campaign drafting", "Social media replies", "Content ideas", "Lead nurturing"],
        responsibilities: ["Draft marketing copy", "Respond on social channels", "Suggest campaign ideas", "Nurture warm leads"],
        languages: ["English", "Afrikaans"],
        integrations: ["Facebook", "Instagram", "WhatsApp", "Mailchimp"],
        experienceLevel: "Mid",
        industries: ["retail", "restaurant", "hotel", "beauty-salon", "gym"],
        packId: null,
        monthlyPrice: "included",
    },
    {
        id: "recruitment-assistant",
        title: "Recruitment Assistant",
        department: "hr",
        icon: "🎯",
        shortDescription: "Screens applicants, schedules interviews, and answers candidate FAQs around the clock.",
        skills: ["Application screening", "Interview scheduling", "Candidate FAQs", "Pipeline tracking"],
        responsibilities: ["Intake applications", "Schedule interviews", "Answer role questions", "Send status updates"],
        languages: ["English", "Afrikaans", "Zulu"],
        integrations: ["WhatsApp", "Google Calendar", "Email", "ATS"],
        experienceLevel: "Mid",
        industries: ["recruitment", "government", "manufacturing", "mining"],
        packId: "pack-recruitment-ai",
        monthlyPrice: "included",
    },
    {
        id: "hr-assistant",
        title: "HR Assistant",
        department: "hr",
        icon: "👥",
        shortDescription: "Handles leave policies, onboarding FAQs, and payroll questions for your team.",
        skills: ["Policy guidance", "Onboarding support", "Leave management", "Payroll FAQs"],
        responsibilities: ["Answer HR policy questions", "Guide new hire onboarding", "Process leave requests", "Explain payroll queries"],
        languages: ["English", "Afrikaans"],
        integrations: ["Email", "Slack", "Microsoft 365", "HRIS"],
        experienceLevel: "Mid",
        industries: ["manufacturing", "mining", "government", "retail"],
        packId: "pack-hr-ai",
        monthlyPrice: "included",
    },
    {
        id: "law-assistant",
        title: "Legal Assistant",
        department: "legal",
        icon: "⚖️",
        shortDescription: "Intakes clients, schedules consultations, and collects documents — in minutes, not hours.",
        skills: ["Client intake", "Consultation booking", "Document collection", "Case triage"],
        responsibilities: ["Capture case details", "Schedule consultations", "Send document checklists", "Qualify legal enquiries"],
        languages: ["English", "Afrikaans"],
        integrations: ["WhatsApp", "Google Calendar", "Email", "CRM"],
        experienceLevel: "Mid",
        industries: ["law-firm", "government", "insurance"],
        packId: "pack-law-ai",
        monthlyPrice: "included",
    },
    {
        id: "doctor-assistant",
        title: "Medical Receptionist",
        department: "healthcare",
        icon: "🩺",
        shortDescription: "Books patient appointments, answers FAQs, and handles prescription requests compassionately.",
        skills: ["Patient scheduling", "Medical FAQs", "Prescription requests", "Referral routing"],
        responsibilities: ["Book patient appointments", "Answer clinic FAQs", "Route prescription requests", "Send appointment reminders"],
        languages: ["English", "Afrikaans", "Zulu", "Xhosa"],
        integrations: ["WhatsApp", "Google Calendar", "SMS", "Practice management"],
        experienceLevel: "Mid",
        industries: ["medical", "pharmacy"],
        packId: "pack-clinic-ai",
        monthlyPrice: "included",
    },
    {
        id: "dentist-assistant",
        title: "Dental Assistant",
        department: "healthcare",
        icon: "🦷",
        shortDescription: "Manages dental bookings, treatment FAQs, and follow-up reminders for your practice.",
        skills: ["Dental scheduling", "Treatment FAQs", "Insurance verification", "Recall reminders"],
        responsibilities: ["Book dental appointments", "Answer treatment questions", "Send recall reminders", "Verify medical aid"],
        languages: ["English", "Afrikaans"],
        integrations: ["WhatsApp", "Google Calendar", "SMS"],
        experienceLevel: "Mid",
        industries: ["dentist"],
        packId: "pack-clinic-ai",
        monthlyPrice: "included",
    },
    {
        id: "church-assistant",
        title: "Church Assistant",
        department: "faith",
        icon: "⛪",
        shortDescription: "Shares service times, handles event RSVPs, and supports pastoral enquiries with care.",
        skills: ["Service information", "Event RSVPs", "Pastoral routing", "Prayer requests"],
        responsibilities: ["Share service times", "Manage event registrations", "Route pastoral enquiries", "Answer membership questions"],
        languages: ["English", "Afrikaans", "Zulu", "Xhosa", "Sotho"],
        integrations: ["WhatsApp", "Facebook", "Email"],
        experienceLevel: "Entry",
        industries: ["church", "ngo"],
        packId: "pack-church-ai",
        monthlyPrice: "included",
    },
    {
        id: "principal-assistant",
        title: "School Administrator",
        department: "education",
        icon: "🏫",
        shortDescription: "Supports principals with parent communication, fee queries, and school event coordination.",
        skills: ["Parent communication", "Fee management", "Event coordination", "Policy guidance"],
        responsibilities: ["Answer parent enquiries", "Share fee structures", "Coordinate school events", "Route urgent matters"],
        languages: ["English", "Afrikaans", "Zulu", "Xhosa"],
        integrations: ["WhatsApp", "Email", "Google Calendar"],
        experienceLevel: "Mid",
        industries: ["school", "university", "college"],
        packId: "pack-school-ai",
        monthlyPrice: "included",
    },
    {
        id: "school-admissions",
        title: "Admissions Officer",
        department: "education",
        icon: "📝",
        shortDescription: "Guides parents through admissions, collects documents, and books campus tours.",
        skills: ["Admissions guidance", "Document collection", "Campus tours", "Waitlist management"],
        responsibilities: ["Guide admission applications", "Collect required documents", "Book campus tours", "Manage waitlists"],
        languages: ["English", "Afrikaans", "Zulu", "Xhosa"],
        integrations: ["WhatsApp", "Email", "Google Calendar"],
        experienceLevel: "Mid",
        industries: ["school", "university", "college"],
        packId: "pack-school-ai",
        monthlyPrice: "included",
    },
    {
        id: "funeral-booking",
        title: "Funeral Coordinator",
        department: "operations",
        icon: "💐",
        shortDescription: "Provides compassionate bereavement intake, arrangements, and family support — always available.",
        skills: ["Bereavement intake", "Arrangement coordination", "Family communication", "Service scheduling"],
        responsibilities: ["Handle bereavement enquiries", "Coordinate funeral arrangements", "Support grieving families", "Schedule viewings and services"],
        languages: ["English", "Afrikaans", "Zulu", "Xhosa", "Sotho"],
        integrations: ["WhatsApp", "Phone", "Email"],
        experienceLevel: "Senior",
        industries: ["funeral"],
        packId: "pack-funeral-ai",
        monthlyPrice: "included",
    },
    {
        id: "claims-assistant",
        title: "Claims Assistant",
        department: "finance",
        icon: "🛡️",
        shortDescription: "Intakes insurance claims, answers policy questions, and tracks claim status for clients.",
        skills: ["Claims intake", "Policy FAQs", "Status tracking", "Document collection"],
        responsibilities: ["Intake new claims", "Answer policy questions", "Track claim progress", "Collect supporting documents"],
        languages: ["English", "Afrikaans"],
        integrations: ["WhatsApp", "Email", "CRM"],
        experienceLevel: "Mid",
        industries: ["insurance"],
        packId: "pack-insurance-ai",
        monthlyPrice: "included",
    },
    {
        id: "real-estate-agent",
        title: "Real Estate Agent",
        department: "sales",
        icon: "🏠",
        shortDescription: "Qualifies buyers, shares listings, and books property viewings automatically.",
        skills: ["Buyer qualification", "Listing information", "Viewing bookings", "Market updates"],
        responsibilities: ["Qualify buyer leads", "Share property listings", "Book viewings", "Follow up on enquiries"],
        languages: ["English", "Afrikaans"],
        integrations: ["WhatsApp", "CRM", "Google Calendar"],
        experienceLevel: "Mid",
        industries: ["real-estate"],
        packId: "pack-estate-agent-ai",
        monthlyPrice: "included",
    },
    {
        id: "property-manager",
        title: "Property Manager",
        department: "operations",
        icon: "🔑",
        shortDescription: "Handles tenant enquiries, maintenance requests, and lease FAQs for property portfolios.",
        skills: ["Tenant communication", "Maintenance routing", "Lease FAQs", "Rent reminders"],
        responsibilities: ["Answer tenant queries", "Log maintenance requests", "Send rent reminders", "Schedule inspections"],
        languages: ["English", "Afrikaans"],
        integrations: ["WhatsApp", "Email", "Property management"],
        experienceLevel: "Mid",
        industries: ["real-estate"],
        packId: "pack-estate-agent-ai",
        monthlyPrice: "included",
    },
    {
        id: "hotel-concierge",
        title: "Hotel Concierge",
        department: "hospitality",
        icon: "🏨",
        shortDescription: "Manages reservations, answers guest questions, and recommends local experiences.",
        skills: ["Reservation management", "Guest services", "Local recommendations", "Upselling"],
        responsibilities: ["Handle room bookings", "Answer guest FAQs", "Recommend activities", "Coordinate special requests"],
        languages: ["English", "Afrikaans", "French", "German"],
        integrations: ["WhatsApp", "Booking systems", "Email"],
        experienceLevel: "Mid",
        industries: ["hotel", "travel"],
        packId: null,
        monthlyPrice: "included",
    },
    {
        id: "restaurant-ordering",
        title: "Restaurant Host",
        department: "hospitality",
        icon: "🍽️",
        shortDescription: "Takes table reservations, answers menu questions, and handles dietary requests.",
        skills: ["Table reservations", "Menu knowledge", "Dietary handling", "Order coordination"],
        responsibilities: ["Book tables", "Answer menu questions", "Handle dietary requests", "Confirm reservations"],
        languages: ["English", "Afrikaans"],
        integrations: ["WhatsApp", "POS", "Google Calendar"],
        experienceLevel: "Entry",
        industries: ["restaurant"],
        packId: "pack-restaurant-ai",
        monthlyPrice: "included",
    },
    {
        id: "inventory-manager",
        title: "Inventory Manager",
        department: "operations",
        icon: "📦",
        shortDescription: "Tracks stock levels, answers availability questions, and triggers reorder alerts.",
        skills: ["Stock tracking", "Availability queries", "Reorder alerts", "Supplier coordination"],
        responsibilities: ["Answer stock availability", "Track inventory levels", "Trigger reorder alerts", "Coordinate with suppliers"],
        languages: ["English"],
        integrations: ["ERP", "WhatsApp", "Email"],
        experienceLevel: "Mid",
        industries: ["retail", "manufacturing", "pharmacy", "automotive"],
        packId: null,
        monthlyPrice: "included",
    },
    {
        id: "technical-support",
        title: "Technical Support",
        department: "support",
        icon: "🔧",
        shortDescription: "Troubleshoots technical issues, guides users through fixes, and escalates when needed.",
        skills: ["Issue diagnosis", "Step-by-step guidance", "Knowledge base search", "Escalation routing"],
        responsibilities: ["Diagnose technical issues", "Guide users through fixes", "Search knowledge base", "Escalate to engineers"],
        languages: ["English", "Afrikaans"],
        integrations: ["WhatsApp", "Email", "Helpdesk", "Slack"],
        experienceLevel: "Senior",
        industries: ["manufacturing", "security", "logistics"],
        packId: "pack-customer-support-ai",
        monthlyPrice: "included",
    },
    {
        id: "procurement-assistant",
        title: "Procurement Assistant",
        department: "operations",
        icon: "🛒",
        shortDescription: "Handles supplier enquiries, RFQ intake, and purchase order tracking.",
        skills: ["Supplier communication", "RFQ management", "PO tracking", "Vendor qualification"],
        responsibilities: ["Intake supplier enquiries", "Manage RFQs", "Track purchase orders", "Qualify new vendors"],
        languages: ["English"],
        integrations: ["Email", "ERP", "WhatsApp"],
        experienceLevel: "Mid",
        industries: ["construction", "mining", "manufacturing", "government"],
        packId: "pack-construction-ai",
        monthlyPrice: "included",
    },
];

export const WORKFORCE_JOURNEY = [
    { step: "Hire", icon: "fa-user-plus", description: "Browse roles by department and hire AI employees in minutes — not months." },
    { step: "Onboard & Train", icon: "fa-graduation-cap", description: "Upload your knowledge base, connect channels, and train on your business in under 10 minutes." },
    { step: "Manage", icon: "fa-sliders", description: "Mission Control gives you real-time visibility across every AI employee and conversation." },
    { step: "Performance", icon: "fa-chart-line", description: "Track accuracy, response times, leads captured, and revenue generated — per employee." },
    { step: "Growth", icon: "fa-seedling", description: "Scale your digital workforce as your business grows — add departments without adding headcount." },
];

export function getDepartmentRoles() {
    return DEPARTMENT_ROLES.map((group) => ({
        ...group,
        departmentLabel: DEPARTMENTS[group.department]?.label || group.department,
        departmentIcon: DEPARTMENTS[group.department]?.icon || "📋",
    }));
}

export function getAiEmployeesCatalog() {
    return AI_EMPLOYEES_CATALOG.map((emp) => ({
        ...emp,
        departmentLabel: DEPARTMENTS[emp.department]?.label || emp.department,
    }));
}

export function getEmployeesByDepartment(departmentId) {
    return getAiEmployeesCatalog().filter((emp) => emp.department === departmentId);
}

export function formatEmployeePrice(price, currency = "ZAR") {
    if (price === "included" || price === null || price === undefined) return "Included in plan";
    if (typeof price === "number") {
        return `R${price.toLocaleString("en-ZA")}/mo`;
    }
    return String(price);
}
